### ISSUE TITLE
How do I update an existing plan

### ISSUE THREAD

**Issue by shrihubble** [killbilling/recurly-java-library#105]
Hi

I want to update the plan which is already created in the recurly. I am not able to find the suitable methos to update it. I had a look at the test cases in https://github.com/killbilling/recurly-java-library/blob/master/src/test/java/com/ning/billing/recurly/TestRecurlyClient.java but didn't find any test case for updating the plan. 
Please help me with it.

**Comment by bhelx** [comment]
As far as I can tell there isn't a route to update the `Plan` models

@pierre is this true? I'd be happy to add it.

**Comment by pierre** [comment]
It looks like it's missing indeed!

**Comment by bhelx** [comment]
Thanks @pierre 

@shrihubble I can put it on my task list for next week. Will post back here.

**Comment by shrihubble** [comment]
Thank you.

**Comment by bhelx** [comment]
@shrihubble https://github.com/killbilling/recurly-java-library/pull/109

**Comment by bhelx** [comment]
Closed with https://github.com/killbilling/recurly-java-library/pull/109
