### ISSUE TITLE
Invoice missing original_invoice in case of a refund

### ISSUE THREAD

**Issue by mzouitni** [killbilling/recurly-java-library#106]
When a refund is issued recurly creates a new invoice and associates it with the original invoice for which the refund was applied. Making a call to recurly to retrieve the detail of the new invoice returns an element "original_invoice" that links back to the original invoice. Currently the Invoice.java class doesn't have support for this, anyway this can be included? Any reason why it was not included before? Can I add it in?

**Comment by bhelx** [comment]
Hey @mzouitni 

It may have been overlooked or the API feature may have been added and unnoticed. I would be happy to review your pull request.

**Comment by mzouitni** [comment]
I have created PR #107 for this fix, let me know if I need to update anything else.
By the way, when is your next release?

**Comment by mzouitni** [comment]
Any idea when your next release is going to be?

**Comment by bhelx** [comment]
That's a question for @pierre

**Comment by pierre** [comment]
I was mainly waiting for https://github.com/killbilling/recurly-java-library/pull/108, since we have lots of changes. I'll cut 0.5.0 shortly afterwards.

**Comment by pierre** [comment]
@bhelx Anything else you wanted in 0.5.0?

**Comment by bhelx** [comment]
No, we can wait for the next release.

**Comment by bhelx** [comment]
Closed with https://github.com/killbilling/recurly-java-library/pull/107

**Comment by mzouitni** [comment]
#78 #90 and #107 are key for us.

**Comment by pierre** [comment]
0.5.0 is on its way to Maven Central. It should be available in a few hours.

**Comment by mzouitni** [comment]
Thank you!
