### ISSUE TITLE
Force TLS 1.1 or later

### ISSUE THREAD

**Issue by jahskee3** [killbilling/recurly-java-library#114]
Please confirm if adding these JVM args will force TLS 1.1 and TLS 1.2 client connection to Recurly Server? 

-Ddeployment.security.TLSv1.1=true -Ddeployment.security.TLSv1.2=true 

Thanks,
Jaizon

**Comment by bhelx** [comment]
@jahskee3

Which version of the library are you using?

**Comment by jahskee3** [comment]
hi Bheix, its 0.5.1 Snapshot.

**Comment by bhelx** [comment]
@jahskee3 

The latest version includes code to force TLS1.2. There is an option to pass in a protocol string which you will find in the README:

```
You may optionally pass the TLS protocol used with the setting -Dkillbill.payment.recurly.tlsProtocol. Keep in mind that Recurly only supports TLSv1.1 and above. This setting defaults to TLSv1.2
``` 

Which version of Java are you running? Are you experiencing a problem?

**Comment by bhelx** [comment]
@jahskee3 for reference: https://github.com/killbilling/recurly-java-library/pull/110/

**Comment by jahskee3** [comment]
@bhelx , we are using Java 7. I will try passing the JVM param. Thank you!

**Comment by bhelx** [comment]
For anyone following here, PCI pushed this date all the way back to `June 30th, 2018` so this issue is on the backburner for now.
