### ISSUE TITLE
Provide HTTP status code in RecurlyApiExceptions

### ISSUE THREAD

**Issue by steelThread** [killbilling/recurly-java-library#116]
Would be beneficial for clients of this lib to include the reculy response http status code in the RecurlyApiExceptions thrown from RecurlyClient.  I'm trying to setup some retry logic for some situations, 500 level statuses namely, and I can't find a deterministic way for determining when I encounter this situation.

**Comment by bhelx** [comment]
Hey @steelThread

Which situations do you with to retry on? I may be able to help you determine them without this feature. If not we can consider adding something in to help.

**Comment by steelThread** [comment]
@bhelx - Thanks for getting back so quickly.  I have a few things here, I want to deal with intermittent network errors on our side.   Looks like I get back a null when the request fails with a ConnectException (ExecutionException really).  Think I have that covered.  The other conditions would be any of the 500 statuses, with these is there way to determine from the RecurlyApiException what the error was?  Do they return an xml doc that gets mapped to the RecurlyAPIError?  Thanks in advance for the help.

**Comment by steelThread** [comment]
@bhelx - any ideas here?

**Comment by jaaknt** [comment]
+1 to idea, to include http response status code in RecurlyAPIException if
response.getStatusCode() >= 300

**Comment by bhelx** [comment]
@steelThread Sorry this fell of my radar. Our API errors have descriptive information in them but there are situations where you may not get it (we've been having recent Cloudflare HTTP level errors for example). 

For that reason, I'm fine with adding a the state code on the ApiError. Sounds like it would be a good addition. Unless one of y'all wants to take the task I am happy to add it.

**Comment by steelThread** [comment]
That would be great @bhelx.

**Comment by bhelx** [comment]
@steelThread This is on my queue. Will link back here when the PR is published.

**Comment by qualidafial** [comment]
Can we do something about the null return value on a 500? Seems like this should also result in a `RecurlyAPIException`.

**Comment by pierre** [comment]
@qualidafial Did you try https://github.com/killbilling/recurly-java-library/pull/120/files?

**Comment by bhelx** [comment]
I believe this was closed with #120 and #123

Please reopen if this is not the case.
