### ISSUE TITLE
RecurlyClient persistent connection in Tomcat Spring

### ISSUE THREAD

**Issue by jahskee3** [killbilling/recurly-java-library#119]
Hi Dev,

Is it  ok to have 1 persistent Recurly connection in Tomcat thru SpringFramework 

Will there be no issue like when it gets disconnected due to Tomcat server downtime,
does it maintain recurly connection without restarting Tomcat instance?

Thanks,
Jai

**Comment by aaron-suarez** [comment]
Closing out this issue due to inactivity. @jahskee3 if you ever found out the answer to your question, consider posting your findings here for people who are also running Tomcat and Spring
