### ISSUE TITLE
Android Studio DataTypeConverter error

### ISSUE THREAD

**Issue by edmundliang** [killbilling/recurly-java-library#137]
I am trying to create an instance of RecurlyClient using the recurly java library on my payment page in my android app on android studio, but I am receiving an error:

 java.lang.NoClassDefFoundError: Failed resolution of: Ljavax/xml/bind/DatatypeConverter;
 at com.ning.billing.recurly.RecurlyClient.<init>(RecurlyClient.java:144)
 at com.ning.billing.recurly.RecurlyClient.<init>(RecurlyClient.java:140)
 at com.ning.billing.recurly.RecurlyClient.<init>(RecurlyClient.java:136)

I think it has to deal with:
public RecurlyClient(String apiKey, String host, int port, String version) {
        this.key = DatatypeConverter.printBase64Binary(apiKey.getBytes());
        this.baseUrl = String.format("https://%s:%d/%s", new Object[]{host, Integer.valueOf(port), version});
        this.xmlMapper = RecurlyObject.newXmlMapper();
        this.userAgent = this.buildUserAgent();
    }

**Comment by pierre** [comment]
Even if this is fixed, the underlying Async HTTP client isn't compatible with Android.

@bhelx can chime in but it seems that you would need to use https://github.com/recurly/recurly-client-android instead?

**Comment by bhelx** [comment]
@edmundliang this library is not intended to be used client side (on the android device). It's not safe to ship your recurly API key with an application.
