### ISSUE TITLE
Getting / deleting account adjustments has been changed in recurly's API v2.X

### ISSUE THREAD

**Issue by huijon** [killbilling/recurly-java-library#140]
For getting adjustments, the existing code uses the endpoint:
GET /accounts/{accountCode}/adjustments

But you can now get the adjustments by uuid:
GET /v2/adjustments/{adjustmentUuid}

Similarly, for deleting, the existing code uses the endpoint:
DELETE /accounts/{accountCode}/adjustment

but its been updated to:
DELETE /v2/adjustments/{adjustmentUuid}

**Comment by bhelx** [comment]
@huijon I added these routes in PR #150

**Comment by bhelx** [comment]
Thanks for pointing it out!

**Comment by bhelx** [comment]
Closing with #150
