### ISSUE TITLE
Invoice model missing 'closedAt' datetime property

### ISSUE THREAD

**Issue by peterjkirby** [killbilling/recurly-java-library#143]
According to the Recurly documentation [here](https://dev.recurly.com/docs/list-invoices), an invoice should have a datetime property called `closed_at`. 

Unless I am mistakenly looking in the wrong place, I do not think that the current Invoice implementation has such a property.

**Comment by bhelx** [comment]
I don't see it either. Would be happy to review a PR to add it or I can add it if you don't have the time.

**Comment by bhelx** [comment]
@peterjkirby I went ahead and added this

**Comment by bhelx** [comment]
Closing with #149
