### ISSUE TITLE
Subscriptions only allow you to add one coupon code

### ISSUE THREAD

**Issue by huijon** [killbilling/recurly-java-library#145]
There's only one method "setCouponCode" on a subscription. However, Recurly allows you to add 
[multiple coupons for a subscription](https://docs.recurly.com/docs/coupons).

**Comment by bhelx** [comment]
@huijon Sorry, I have just seen this. You can have multiple coupons on an account, but I do not think the API allows adding multiple coupons to a subscription. Are you seeing that in the documentation?

**Comment by huijon** [comment]
Hi @bhelx, 
I think the documentation may have been updated recently to make it clearer. You can see it here: 
https://dev.recurly.com/docs/update-subscription under the coupons section.

e.g.
`<coupon_codes>
    <coupon_code>savemore</coupon_code>
    <coupon_code>holidayspecial</coupon_code>
</coupon_codes>`

**Comment by bhelx** [comment]
@huijon my mistake. Subscription does support a `coupon_codes`. I'll add it to this library.

**Comment by huijon** [comment]
thanks!
