### ISSUE TITLE
Invoice ID needs to be a string

### ISSUE THREAD

**Issue by davegildea** [killbilling/recurly-java-library#147]
Hi Guys

Love your lib, its very helpful. One issue we have come across through is that the invoice id needs to be a string not integer. When we do a get invoice by invoiceid  there country code is included, like IE1023 and not just 1023. So if we just get the invoice by the integer part its picks the wrong one, if we include the country code it works perfectly.

It is something you have come across before ? Have you any plans to convert the type from Integer to String?

Thanks

Dave

**Comment by bhelx** [comment]
Hey @davegildea 

So, we have two parts of an invoice id: A number and an optional prefix. The prefix part was added later so it looks like maybe this library was not updated to reflect that change. I can add another method to reflect this. Thanks for pointing it out!

https://github.com/killbilling/recurly-java-library/blob/master/src/main/java/com/ning/billing/recurly/RecurlyClient.java#L575

**Comment by bhelx** [comment]
I'll be linking back here when the PR is out.

**Comment by bhelx** [comment]
Closed with #148

**Comment by davegildea** [comment]
Thanks guys, looks great!
