### ISSUE TITLE
revenue_schedule_type Null Pointer Exception

### ISSUE THREAD

**Issue by jfreeby** [killbilling/recurly-java-library#152]
We just recently upgraded to 0.6.2 and are getting exceptions when looking up some subscriptions:

com.fasterxml.jackson.databind.JsonMappingException: N/A (through reference chain: com.ning.billing.recurly.model.Subscriptions["subscription"]->com.ning.billing.recurly.model.Subscription["revenue_schedule_type"])

Caused by: java.lang.NullPointerException
	at com.ning.billing.recurly.model.Subscription.setRevenueScheduleType(Subscription.java:338)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:97)
	... 45 more

When I perform a curl request for the subscription that fails, Recurly is returning an empty element:

 <revenue_schedule_type></revenue_schedule_type>

For other requests that succeed there is a value in the element

 <revenue_schedule_type>evenly</revenue_schedule_type>

Please let me know if you need additional information.

Thanks,

Jim

**Comment by jfreeby** [comment]
More info .....

The null pointer is happening in the method, where the revenueScheduleType is null and the call to toUpperCase fails.

public void setRevenueScheduleType(final String revenueScheduleType) {
    this.revenueScheduleType = RevenueScheduleType.valueOf(revenueScheduleType.toUpperCase());
}

**Comment by bhelx** [comment]
Thanks @jfreeby

I'll take a look at this and try to reproduce it

**Comment by jfreeby** [comment]
A simple null check fixed our issue.  Do you have any idea when this might make it to a release?  I have a custom version for now.

**Comment by bhelx** [comment]
@jfreeby if you send a PR, it should be a short review.

**Comment by jfreeby** [comment]
@bhelx Can you point to any instructions on sending a PR?  I just checked the code out with SVN and made the changes locally.  I'd be happy to send the code in any way possible.

**Comment by bhelx** [comment]
@jfreeby You'll want to follow the standard Github procedure of forking the repository, creating a branch, and sending the PR into the master branch of this repo: https://help.github.com/articles/creating-a-pull-request-from-a-fork/

If you can't get this working, or do not feel it's worth your time, feel free to email me a diff and I'd be happy to create a commit crediting you. My email is ben@recurly.com

**Comment by jfreeby** [comment]
@bhelx Thanks for the pointers

I forked and created a pull request.  Let me know you need anything else.

**Comment by bhelx** [comment]
Thanks @jfreeby
