### ISSUE TITLE
Release 0.6.3

### ISSUE THREAD

**Issue by mattcarrier** [killbilling/recurly-java-library#164]
We need the coupon temporal duration stuff from #163, can a new release be cut?

**Comment by pierre** [comment]
Yes @mattcarrier, we're working on it.

**Comment by pierre** [comment]
0.7.0 has been released.

**Comment by mattcarrier** [comment]
@pierre sorry to be a PITA, we just have a feature that needs this functionality.  I appreciate your time spent.
