### ISSUE TITLE
Get All Purchase Transactions fails 

### ISSUE THREAD

**Issue by jfreeby** [killbilling/recurly-java-library#166]
<version>0.7.0</version>

When calling recurlyClient.getTransactions(TransactionState.SUCCESSFUL, TransactionType.PURCHASE , queryParams);

The call fails with a message:

<?xml version="1.0" encoding="UTF-8"?>
<error>
  <symbol>type_invalid</symbol>
  <description>Invalid type (must be one of authorization, purchase, refund)</description>
</error>

During execution, the following method is called (with a new QueryParams that has a default page size)

The resource already has some QueryParams added
    private String constructGetUrl(final String resource, QueryParams params) {
        return baseUrl + resource + params.toString();
    }

The resulting URL looks like:

/v2/transactions?per_page=20&end_time=2017-01-16T00:00:00.000-08:00&begin_time=2017-01-04T00:00:00.000-08:00&state=successful&type=purchase?per_page=20 HTTP/1.1

You can see the 2nd "?per_page=20" added to the URL.  This makes the "type" value invalid.

**Comment by bhelx** [comment]
Thanks @jfreeby I'll try to reproduce this and get a fix ready

**Comment by bhelx** [comment]
@jfreeby thanks for such a descriptive issue! It allowed me to reproduce and fix this quickly. If you have a moment, please take a look at https://github.com/killbilling/recurly-java-library/pull/168 to verify that it resolves the problem.

**Comment by jfreeby** [comment]
Thanks @bhelx - Looking now

**Comment by jfreeby** [comment]
@bhelx Looks good.  I also coded a solution, but yours is more elegant.

Thanks for the rapid response.  When can I check the code out?
