### ISSUE TITLE
Add support for Invoice Refunds 

### ISSUE THREAD

**Issue by cfrasineanu-intx** [killbilling/recurly-java-library#169]
Version 0.7.0 does not support invoice refunds. We can not use Transaction Refunds because our account was created after November 11, 2014.
According to Recurly docs:`We are moving to refunds through the Invoice object. Transaction refunds will no longer work if you have switched to Invoice Refunds in your Site Settings. If you created your site after November 11, 2014, you are automatically on Invoice refunds. Please see our API documentation on Invoices.`

**Comment by bhelx** [comment]
Hey @cfrasineanu-intx 

I believe you are right, this library seems to still use transaction refunds. It does support setting a `RefundOption` on a subscription termination, but it doesn't support the invoice refunding calls now available in the API.

I'll start a branch today to address this issue. It will link back here when it's posted for review.

**Comment by cfrasineanu-intx** [comment]
I already have implemented the refund via https://dev.recurly.com/docs/open-amount-refunds
Let me know if u want to do it yourself or you can review my implementation.

**Comment by bhelx** [comment]
@cfrasineanu-intx thanks for offering. I actually just noticed that we never fully made the switch over to supporting prefixed invoice numbers so I've decided to do that first #170 . I'm going to branch the refund changes off of that since I don't want to add more deprecated invoice methods. In the future feel free to submit any changes you would like to make and I'd be more than happy to review them for you and get them in!

**Comment by cfrasineanu-intx** [comment]
@bhelx Sounds good. Thanks!

**Comment by cfrasineanu-intx** [comment]
@bhelx  I tried to use Guava v.21 in our application and got a runtime error because Recurly Java Library is using com.google.common.base.Objects#firstNonNull (which was removed Guava 21) in RecurlyClient class. This  method was deprecated in v.18 and it is recommended to use com.google.common.base.MoreObjects#firstNonNull instead. Is it possible to make the change in this branch or should I open another issue? Thank you!

**Comment by bhelx** [comment]
@cfrasineanu-intx I'd prefer we open another PR for that. We generally do one PR per change.

> BTW, do you know when this change will be available to us? Thank you!

I'm should be getting the PR out today.

**Comment by cfrasineanu-intx** [comment]
Thanks! Created https://github.com/killbilling/recurly-java-library/issues/171

**Comment by cfrasineanu-intx** [comment]
PR for invoice refund will be out today?

**Comment by cfrasineanu-intx** [comment]
I appreciate it
