### ISSUE TITLE
Replace uses of Guava's Objects#firstNonNull with MoreObjects#firstNonNull

### ISSUE THREAD

**Issue by cfrasineanu-intx** [killbilling/recurly-java-library#171]
I tried to use Guava v.21 in our application and got a runtime error because RecurlyClient.java uses  com.google.common.base.Objects#firstNonNull (which was removed Guava 21). This method was deprecated in v.18 and it is recommended to use com.google.common.base.MoreObjects#firstNonNull instead. Thank you!

**Comment by bhelx** [comment]
@pierre do you know if this could be related to #73 at all?

**Comment by pierre** [comment]
Not quite: the issue here is the incompatibility between both Guava versions (in-app vs the one used in the library). We should probably upgrade our version and get rid of the deprecated usages.
