### ISSUE TITLE
Remaining_billing_cycles unavailable in subscription element

### ISSUE THREAD

**Issue by kansology** [killbilling/recurly-java-library#178]
Remaining_billing cycles is an element to subscription which tells how many renewals are left in the subscription. Null means the subscription will auto-renew. 0 means the subscription will expire at the next renewal. Will always change immediately, even if timeframe = renewal.

Currently client doesn't handle it. The fix is fairly simple and i already did it along with test coverage.
If the push rights provided i can add it.

Below is the snippet of the tag:

<total_billing_cycles nil="nil"/>
  **<remaining_billing_cycles nil="nil"/>**
  <current_period_started_at type="datetime">2016-07-11T22:36:22Z</current_period_started_at>

**Comment by bhelx** [comment]
@kansology Thanks for reporting. A PR would be great! If you can't send it along I'd be happy to add the PR.

**Comment by kansology** [comment]
@bhelx  just did the PR. Please have a look.

**Comment by kansology** [comment]
Thanks @bhelx.
Can you please cut a release for this?

**Comment by bhelx** [comment]
Closed with #179

**Comment by bhelx** [comment]
@kansology I will work out a release with @pierre . I'd like to get our API v2.5 upgrade changes in for a release next week. We can piggy back this change onto that release.
