### ISSUE TITLE
Support refund of invoice line items

### ISSUE THREAD

**Issue by cfrasineanu-intx** [killbilling/recurly-java-library#181]
See https://dev.recurly.com/docs/line-item-refunds. Thank you!

**Comment by bhelx** [comment]
@cfrasineanu-intx I've added support for this in #175

https://github.com/killbilling/recurly-java-library/blob/master/src/main/java/com/ning/billing/recurly/RecurlyClient.java#L824

**Comment by bhelx** [comment]
The description in the PR in #175 shows how to use it:

```java
final invoice = recurlyClient.getInvoice("1234");
final ArrayList<AdjustmentRefund> lineItems = new ArrayList<AdjustmentRefund>();

// let's just refund the first adjustment
// we can use "toAdjustmentRefund" on the adjustment to turn it
// into an AdjustmentRefund  
final AdjustmentRefund adjustmentRefund = invoice.getLineItems().get(0).toAdjustmentRefund();

// we could change the quantity here or the prorating settings if we want, defaults to full quantity
// adjustmentRefund.setQuantity(1);
lineItems.add(adjustmentRefund);

final Invoice refundInvoice = recurlyClient.refundInvoice(invoice.getId(), lineItems, RefundApplyOrder.transaction);
```

**Comment by cfrasineanu-intx** [comment]
This method is not available in version 0.8.0:
`public Invoice refundInvoice(final String invoiceId, List<AdjustmentRefund> lineItems, final RefundApplyOrder order)`

**Comment by bhelx** [comment]
@cfrasineanu-intx I don't think it's been released to mavencentral yet. @pierre can you confirm?

**Comment by cfrasineanu-intx** [comment]
@bhelx It seems that #175 has not been released it. How soon can this be released because we need that functionality? Thanks

**Comment by pierre** [comment]
@cfrasineanu-intx 0.9.0 has been released.

**Comment by cfrasineanu-intx** [comment]
@pierre Thanks. It seems that the build failed.

**Comment by pierre** [comment]
@cfrasineanu-intx Yes, Travis tests are flaky, but the release went through.

**Comment by bhelx** [comment]
There is one bad integration test but I've verified it's okay. Going to send a PR for a fix as soon as I get the chance.
