### ISSUE TITLE
Allow configuration of user agent

### ISSUE THREAD

**Issue by glasser** [killbilling/recurly-java-library#184]
As the user agent shows up in the recurly developer interface, it would be great if we could configure it to make it easier to ensure that our use of the library (and other vendors who use the library as well) is with proper API keys.

**Comment by bhelx** [comment]
@glasser What do you wish to put in the user agent? I'm confused about the latter part related to "proper API keys".

The format of the user agent was designed so we can do analytics on our end. This allows us to segment users by things like their Java version and their library version. We use this information to make decisions when changing this library so we need to at least keep that part.

**Comment by glasser** [comment]
This is probably easier with a bit of a story.

On Friday, we noticed some of our attempts to use Recurly (not via KillBill) were failing, and Recurly informed us that we were hitting their rate limits.  We asked them to describe the requests that were coming in and were alarmed to see requests that didn't match anything in any of our code, from an IP we didn't recognize, and with the User Agent "KillBill".

We spent a scared hour worried that we were being attacked by some malicious actor who happened to use this Java library.

Eventually we realized that this was actually a service we were legitimately using ("Fivetran") whose implementation (which uses this library) doesn't throttle their access to Recurly.  And unfortunately, my colleague who set up that integration didn't create a separate API key for this service so it took us far too long to track down what was responsible.

We will avoid this in the future by using per-service API keys, of course. *BUT* it also would have been great if this library had allowed third-party services like Fivetran to set a custom User Agent (perhaps appended to your standard version user agent) and if Fivetran had chosen to use this option — that would have been another path to us quickly understanding why we were hitting our API limits.

**Comment by bhelx** [comment]
@glasser Thanks for explaining that. Sorry that happened to you. We definitely recommend creating 1 API key per service. Not just for security reasons but also for you (and us) to easily identify problem services.

Here is what I'd suggest you do. Make a new key for this service. Mark it as `read-only` if they only need read access. You can also name it something descriptive like "fivetran". And under the section `Will this key be used with a third-party application?` you can put in Fivetran or the name of the service you are giving this key to. I'd also suggest talking to support about your rate limits and whether you think they are appropriate. They are adjustable on request if we feel we need to loosen them for you.

I'm not sure if adding a custom user agent would be helpful if you use the keys as suggested (which we want to encourage people to do). I think if this is still a major problem for you, you should send a request to support that we add a feature to address it. I can think of a couple things off the top of my head:

1. Allow API keys to be rate limited individually
2. Have better error reporting on which key is causing a problem. Maybe the rate limit message can yell you the name of the API key that caused the problem.

**Comment by glasser** [comment]
Yup, that's exactly what we are doing now — and more people in our organization now understand why the feature of having multiple API keys exists :)  It definitely was a little confusing to read "KillBill" as the user agent rather than "Recurly Java client" or something, since the actual KillBill library isn't actually involved.

Rate limiting API keys separately would be great — is that something on your roadmap?  (I take it you work for Recurly?)

While I don't believe the automated rate limiting message included the API keys, the Recurly support person we followed up with did provide it, which helped a bit... except for the fact that we had inadvertently reused our keys across services.

**Comment by bhelx** [comment]
>Yup, that's exactly what we are doing now — and more people in our organization now understand why the feature of having multiple API keys exists :) It definitely was a little confusing to read "KillBill" as the user agent rather than "Recurly Java client" or something, since the actual KillBill library isn't actually involved.

I can see how that would be the case. This has to do with the fact that this library was written by KillBill (http://killbill.io/) and we wanted to keep the user agent the same for analytics purposes. It's still not an official library but if it does become one we may change that.

>Rate limiting API keys separately would be great — is that something on your roadmap? (I take it you work for Recurly?)

Yes, I work at Recurly. I agree that would be a great feature but it was designed this way for capacity reasons. I could see this being added as a feature for our Enterprise plan.

**Comment by glasser** [comment]
Just to be clear — everything is fine with us now as far as this library is concerned (we would like Fivetran to improve their integration's throttling, but that's a separate issue).

I'm merely suggesting that we might not be the only Recurly user to set up a non-engineer-focused tool like Fivetran without proper API key usage, and that a small improvement to user-agent identification might help other users understand issues like this in the future without a scary hour like we had.  But it doesn't particular affect us one way or the other at this point.

(Also perhaps somebody doing a web search for `killbill recurly api limit` will stumble across this page and use it to solve their problem :) )

**Comment by bhelx** [comment]
I don't think we are going to implement this because I feel like it would be better to work on informing merchants to use multiple API keys over implementing this in every library and asking all 3rd party services to customize the agent.

Also, once we implement OAuth this won't be a problem.
