### ISSUE TITLE
Provide more info in FailedPaymentNotification

### ISSUE THREAD

**Issue by cfrasineanu-intx** [killbilling/recurly-java-library#190]
Hello, 
In our project we need to use the following data that Recurly returns in the failed_payment_notification webhook:
`<gateway_error_codes nil="true"></gateway_error_codes>
    <failure_type>Declined by the gateway</failure_type>`
I can make the necessary code changes.
Thanks!

**Comment by bhelx** [comment]
@cfrasineanu-intx it's possible our webhooks parsers are a little behind. I'll merge any changes you want to make just tag me on the PR!

**Comment by bhelx** [comment]
Closed with #191
