### ISSUE TITLE
De-serialization failed for all push notifications since 20 July 20:49 GMT+2

### ISSUE THREAD

**Issue by lc-ikrumov** [killbilling/recurly-java-library#203]
Hello all,

I have an urgent issue:
I think Recurly changed something in their push structure because I get errors since 20 Jul 20:49 GMT+2 from the Recurly Java library:

```

09:18:14.492 [http-apr-80-exec-2] WARN  c.n.b.r.model.push.Notification - Enable to read notification, de-serialization failed : Invalid format: "{type=dateTime, =2017-07-06T08:3..." (through reference chain: com.ning.billing.recurly.model.push.invoice.ClosedInvoiceNotification["invoice"]->com.ning.billing.recurly.model.push.invoice.PushInvoice["date"])
09:18:14.499 [http-apr-80-exec-33] WARN  c.n.b.r.model.push.Notification - Enable to read notification, de-serialization failed : Invalid format: "{type=dateTime, =2017-07-21T07:1..." (through reference chain: com.ning.billing.recurly.model.push.payment.SuccessfulPaymentNotification["transaction"]->com.ning.billing.recurly.model.push.payment.PushTransaction["date"])
```

The error happens at least when processing the following pushes:
SuccessfulPayment
FailedPayment
CanceledSubscription
RenewedSubscription
NewInvoice
ClosedInvoice

My library is quite old: 0.5.1-SNAPSHOT

Is this problem solved in a later version (and which one)? I have refrained from upgrading because I was not sure if versions are backwards compatible.

Thank you in advance..

**Comment by lc-ikrumov** [comment]
I compared the push payloads before and after the errors started happening:
OLD: <date type="datetime">2017-07-20T01:35:54Z</date>
NEW: <date type="dateTime">2017-07-21T07:18:44Z</date>

(this is in a 'transaction' node)
The change from 'datetime' to 'dateTime' is global for all DateTime fields.

I see in the source code, in RecurlyObject class, the dateTimeOrNull() method is expecting 'datetime' instead of 'dateTime' and I believe this is why it fails. I will try to change it and see if it works

**Comment by lc-ikrumov** [comment]
Changing RecurlyObject.dateTimeOrNull() fixes the issue and failing tests pass. Tested the fix on a staging environment and no issues.
I will submit a PR soon but until then - what I changed:

`if (map.keySet().size() == 2 && "datetime".equals(map.get("type"))) {`
changes to
`if (map.keySet().size() == 2 && ("dateTime".equals(map.get("type")) || "datetime".equals(map.get("type")))) {`

I kept both formats for backwards compatibility.
I also changed all test data using the old 'datetime' format to use the new format.

**Comment by mzouitni** [comment]
@lc-ikrumov We are running into the same issue as well. Can't you just do equalsIgnoreCase instead of equals twice?

**Comment by lc-ikrumov** [comment]
@mzouitni Yes, that is fine as well. I was more restrictive but it is not necessary.

Strangely, when I pull from master tests run successfully without any changes. Not sure if the issue is present in the current master.

**Comment by mzouitni** [comment]
I was going to suggest having that check change for all types, I have no idea what recurly changed and why but I would not be surprised if they make that change to other types. I think the tests pass because you may not have updated the existing xml documents that the tests are using.

**Comment by lc-ikrumov** [comment]
@mzouitni I think Recurly have reverted their change because I see the 'dateTime' changed back to 'datetime' for pushes sent as of 22 July. The pushes that failed would still need to be processed of course, but since Recurly tries periodically to retry the pushes it could be that it retried with the proper structure (not sure). You can check whether you still have unprocessed webhook updates from Recurly dashboard.

I deployed my update locally and it was OK.

**Comment by drewish** [comment]
@bhelx is out on vacation but he mentioned this to me to follow up up. last week's deploy included an upgraded library. one of the changes was to update the XML generation to follow the spec which called for `dateTime` rather than `datetime`. when we heard this was a breaking change for some merchants we rolled out a fix to revert that. 

i think going forward it would be best to do a string insensitive comparison so eventually we could  follow the spec, but i'll let @bhelx weigh in on that.

**Comment by lc-ikrumov** [comment]
The pull request is merged and the issue is fixed in the latest codebase.
