### ISSUE TITLE
AccountAcquisition API is missing

### ISSUE THREAD

**Issue by ssundaram-xactly** [killbilling/recurly-java-library#206]
I am using 0.11.0 version of the library. I need to populate AccountAcquisition details as part of the recurly account creation so that I can track the channel and campaign ID in recurly. I noticed that the model class for this object is missing and the CRUD methods for this object in RecurlyClient class is missing as well.

**Comment by bhelx** [comment]
@ssundaram-xactly Sorry I'm just getting back. Seems like it is in fact missing. I'll add it today.

**Comment by ssundaram-xactly** [comment]
Thanks @bhelx. When you add the support, can you add it as part of the Account object as well? Recurly supports creating the AccountAcquisiton as part of the Account object itself.

**Comment by bhelx** [comment]
@ssundaram-xactly Yes, I'll add that. Thanks for reminding me.

**Comment by bhelx** [comment]
Closed with #207

**Comment by bhelx** [comment]
@ssundaram-xactly let me know if that makes sense.

**Comment by ssundaram-xactly** [comment]
@bhelx Thanks for fixing this. I am using maven. Is the fix deployed to maven-central as part of the same version 0.11.0 ?
