### ISSUE TITLE
BillingInfo missing "type" attribute

### ISSUE THREAD

**Issue by pennstatephil** [killbilling/recurly-java-library#208]
`<billing_info href="https://your-subdomain.recurly.com/v2/accounts/1/billing_info" type="credit_card">`

**Comment by kansology** [comment]
@bhelx is this issue worked on?
Is there any planned release date for this?

**Comment by bhelx** [comment]
@kansology I have a branch with the changes needed. I'll try to get it tested and up today.

**Comment by bhelx** [comment]
@kansology @pennstatephil #217 parses the `type` attribute on billing info, however, this library does not make use of the associations (what you described above). You can only get the type from a BillingInfo object, not a link to one. If this is a problem let me know and I can help you with a workaround or we can look into how it would look to use the associations.

**Comment by pennstatephil** [comment]
@bhelx Thanks so much for merging that. Could we get a release so we can integrate the new code?

**Comment by bhelx** [comment]
@pennstatephil It will be included in the next release when @pierre pushes to maven central.

**Comment by pennstatephil** [comment]
Hey again -- just happened to check on this, and saw #216 was merged a couple hours ago 🎉  -- does this mean a release is imminent?

**Comment by bhelx** [comment]
@pierre Could you push a release when you get the chance? There should be a minor version bump due to some new validations in the new API version.

**Comment by pierre** [comment]
@pennstatephil 0.12.0 released!

@bhelx Note that #216 was merged into `api_version_2_8` only and hasn't been released yet. What's the timeline for the merge?

**Comment by bhelx** [comment]
@pierre I forgot about that. It's ready now: https://github.com/killbilling/recurly-java-library/pull/218

**Comment by aaron-suarez** [comment]
This looks like it was fixed a while ago, closing this issue out. If it's actually not fixed, please feel free to reopen
