### ISSUE TITLE
Missing address info

### ISSUE THREAD

**Issue by Radagan** [killbilling/recurly-java-library#221]
Using the latest version of this library from maven (12), my test subscriptions do not return any billing, shipping, or account address information. They are all null despite showing up fine on invoices and in the account if you login. Any ideas? I'm new to Recurly...

**Comment by Radagan** [comment]
Tried again with today's release of 0.13.0 and still now address info.

**Comment by bhelx** [comment]
@Radagan When you fetch a subscription, it usually does not contain the account information embedded. You generally need to fetch the account separately. Can you provide some example code showing what you mean?

**Comment by Radagan** [comment]
Thanks, I tried that but still nothing but nulls. 

I'm running this directly in IDEA. 

```
RecurlyClient rc = new RecurlyClient(recurlyKey);
try {
	rc.open();
} catch (NoSuchAlgorithmException e) {
	e.printStackTrace();
} catch (KeyManagementException e) {
	e.printStackTrace();
}

Accounts accounts = rc.getAccounts();
for (Account account: accounts) {
	System.out.print(account.getFirstName() + " " + account.getLastName() + " (" + account.getAccountCode() + ", " + account.getEmail() + ")");
	BillingInfo bi = account.getBillingInfo();
	System.out.println(bi.getAddress1() + "\n" + bi.getCity() + "\n" + bi.getState() + "\n" + bi.getCountry());
}
```

When I log into Recurly, each account shows a full address in the Billing Info section on the right. Any idea what I could be doing wrong? The Account name, code, etc. print correctly--just no Billing Info.

**Comment by bhelx** [comment]
If you look at the account xml, you'll see that it does not contain embedded billing info. Here is an example:

```xml
<account href="https://java-client-sandbox.recurly.com/v2/accounts/v4Sz8o0Ptb">
    <adjustments href="https://java-client-sandbox.recurly.com/v2/accounts/v4Sz8o0Ptb/adjustments"/>
    <account_balance href="https://java-client-sandbox.recurly.com/v2/accounts/v4Sz8o0Ptb/balance"/>
    <invoices href="https://java-client-sandbox.recurly.com/v2/accounts/v4Sz8o0Ptb/invoices"/>
    <shipping_addresses href="https://java-client-sandbox.recurly.com/v2/accounts/v4Sz8o0Ptb/shipping_addresses"/>
    <subscriptions href="https://java-client-sandbox.recurly.com/v2/accounts/v4Sz8o0Ptb/subscriptions"/>
    <transactions href="https://java-client-sandbox.recurly.com/v2/accounts/v4Sz8o0Ptb/transactions"/>
    <account_code>v4Sz8o0Ptb</account_code>
    <state>closed</state>
    <username nil="nil"></username>
    <email>v4Sz@test.com</email>
    <cc_emails nil="nil"></cc_emails>
    <first_name>v4Sz8</first_name>
    <last_name>v4Sz8o</last_name>
    <company_name>v4Sz8o0Ptb</company_name>
    <vat_number>v4Sz8o0PtbQp2zg</vat_number>
    <address>
      <address1>v4Sz8o0Ptb</address1>
      <address2>v4Sz8o0Ptb</address2>
      <city>v4Sz8o0Ptb</city>
      <state>LG</state>
      <zip>94110</zip>
      <country>US</country>
      <phone>5463648793</phone>
    </address>
    <accept_language>en_US</accept_language>
    <hosted_login_token>qswoLuyhkcAahXP5PHhAaRQQ4xvXNoFA</hosted_login_token>
    <created_at type="datetime">2017-11-22T09:38:47Z</created_at>
    <updated_at type="datetime">2017-11-22T09:38:48Z</updated_at>
    <closed_at type="datetime">2017-11-22T09:38:48Z</closed_at>
    <a name="reopen" href="https://java-client-sandbox.recurly.com/v2/accounts/v4Sz8o0Ptb/reopen" method="put"/>
    <has_live_subscription type="boolean">false</has_live_subscription>
    <has_active_subscription type="boolean">false</has_active_subscription>
    <has_future_subscription type="boolean">false</has_future_subscription>
    <has_canceled_subscription type="boolean">false</has_canceled_subscription>
    <has_past_due_invoice type="boolean">false</has_past_due_invoice>
  </account>
```

In order to get the billing info for an account, you have to ask the server via the `RecurlyClient` (specifically the `getBillingInfo(String accountCode)` method. The `Account` instance is just a DTO. Example:

```java
final Accounts accounts = recurlyClient.getAccounts();
for (Account account: accounts) {
  System.out.print(account.getFirstName() + " " + account.getLastName() + " (" + account.getAccountCode() + ", " + account.getEmail() + ")");
  try {
    final BillingInfo bi = recurlyClient.getBillingInfo(account.getAccountCode());
    System.out.println(bi.getAddress1() + "\n" + bi.getCity() + "\n" + bi.getState() + "\n" + bi.getCountry());
  } catch (RecurlyAPIException e) {
    // throws a 404 if the account does not have billing info
    // RecurlyAPIError{description='Couldn't find BillingInfo with account_code = Syk4C8SmUU', symbol='not_found', details='null', httpStatusCode='404'} 
    System.out.println(e);
  }
}
```

Keep in mind, you'll need to catch a 404 exception if the billing info does not exist for the account. Let me know if this works for you.

**Comment by bhelx** [comment]
Also keep in mind that this also applies to other parts of the account. If you want to get shipping addresses for instance:

```java
final ShippingAddresses addresses = recurlyClient.getAccountShippingAddresses(account.getAccountCode());
```

**Comment by Radagan** [comment]
Ah! Thank you! Relying on the Recurly client for everything works like a charm. 

Is there a way to ask Recurly for a full Account object so that those convenience methods have a purpose?

**Comment by bhelx** [comment]
@Radagan there currently isn't a way to do that. We've had to make some tradeoffs for performance reasons. If you are trying to do ETL or some other non-realtime process that requires a wide breadth of data, consider looking at our exports feature.

**Comment by Radagan** [comment]
@bhelx Thanks again. My use here pretty much that, a backend process that sanity checks customer data in the cloud verses Recurly. I'm working on getting Notifications working properly, but don't want to fully rely on that. I appreciate your patience. I'm new to Recurly and current e-commerce systems in general.

**Comment by bhelx** [comment]
No problem. Feel free to file any questions you have as issues and I'll help you out. I understand we are still limited in the documentation on this library.

> My use here is pretty much that, a backend process that sanity checks customer data in the cloud verses Recurly.

If it's a non-realtime thing (like say it needs to be run once a day), I'd take a look at using exports. This is only available through the API if you have the professional or enterprise plan unfortunately.
https://docs.recurly.com/docs/export-overview#section-automated-exports

> I'm working on getting Notifications working properly, but don't want to fully rely on that.

I'd agree with that. I think your instincts are correct there. If 100% accuracy is your goal, you don't want to rely on notifications. They cannot be guaranteed.

**Comment by bhelx** [comment]
One more thing, you may want to look at date-range filtering to ease the number of calls you'll need to make. Every pageable endpoint takes a `QueryParams` object which allows you to filter and sort the objects. For example, you could get all the accounts that were updated in the last X days sorted in descending order.
https://github.com/killbilling/recurly-java-library/blob/d385ed7752090d241d2bfc92be55bb2c46e30c49/src/main/java/com/ning/billing/recurly/RecurlyClient.java#L200
