### ISSUE TITLE
Missing gateway field in FailedPaymentNotification

### ISSUE THREAD

**Issue by pennstatephil** [killbilling/recurly-java-library#224]
https://dev.recurly.com/page/webhooks#section-failed-payment
Inside the FailedPaymentNotification's Transaction, the Gateway tag is missing.

**Comment by bhelx** [comment]
@pennstatephil thanks for letting me know. Happy to review it for y'all.

**Comment by kansology** [comment]
Hi

Our requirement change and now we need to get the gateway error fields from the transaction endpoints and they also dont have same fields. Look for the transaction object.
is there any work already going on it?

**Comment by kansology** [comment]
Hi @bhelx 

Created a pull request for this.
Please review and merge.

**Comment by kansology** [comment]
@bhelx 

I just saw current build is failing after merge.
It doesnt seems to be directly connected with my change.

Can you please check, additionally by when we can expect the release for the library.

**Comment by bhelx** [comment]
@kansology we don't automatically publish releases. We usually wait until a few things pile up before we do a release. We can see about doing a release this week if you need it in the official release.

**Comment by kansology** [comment]
@bhelx That would be great.
We could really use a release with latest changes.

**Comment by pierre** [comment]
Happy to do a release, but it looks like we need to fix Travis first. @bhelx might be an issue with the sandbox?

**Comment by bhelx** [comment]
One test was failing locally and on Travis. Ill take a look at it and address in it’s own PR.

**Comment by kansology** [comment]
@bhelx @pierre 
Do we have any expected timeframe for the API release?

**Comment by bhelx** [comment]
Closed with #226 

@kansology Please let me know if you haven't picked up this change yet.
