### ISSUE TITLE
How to edit the add-on of Plan

### ISSUE THREAD

**Issue by mpogra** [killbilling/recurly-java-library#227]
Hello,

Thanks for writing such nice lib and it's really helping us. We have integrated it nicely but came across the case that we want to edit the add-on associated with plan but we don't see anything like "updateAddOn" in recurly client. Is there anything we are missing or it is not yet available? As Recurly API does have edit add on API exposed at this [link](https://dev.recurly.com/v2.4/docs/update-an-add-on) . 

Thanks again,
MP

**Comment by bhelx** [comment]
At first glance, it just looks like we are missing that `updateAddOn` method. I'd be happy to add it for you or you can send a PR. I should be able to get time to do it today.

**Comment by bhelx** [comment]
I'll go ahead and do this now since I have a some downtime.

**Comment by mpogra** [comment]
Thanks so much for understanding and help. Let us know when change is available.

**Comment by bhelx** [comment]
Closed with #228
