### ISSUE TITLE
Missing Coupon enum Type "unique_code"

### ISSUE THREAD

**Issue by mmichalko** [killbilling/recurly-java-library#235]
This coupon type is created in Recurly by selecting "Bulk unique codes" option.

Exception:
`com.ning.billing.recurly.shaded.com.fasterxml.jackson.databind.exc.InvalidFormatException: Can not construct instance of com.ning.billing.recurly.model.Coupon$Type from String value 'unique_code': value not one of declared Enum instance names: [single_code, bulk]
 at [Source: java.io.StringReader@63edf060; line: 25, column: 41] (through reference chain: com.ning.billing.recurly.model.Coupon["coupon_type"])`

**Comment by hijklmno** [comment]
PR'd in #255.
