### ISSUE TITLE
Mising properties on account's invoices

### ISSUE THREAD

**Issue by jrg091** [killbilling/recurly-java-library#242]
When fetching an account's invoices it's seems there are some missing properties:

- `line_items -> adjustments -> proration_rate`
- `transactions -> transaction -> ip_address`
- `transactions -> transaction -> approval_code`
- `transactions -> transaction -> failure_type`
- `transactions -> transaction -> gateway_error_codes`
- `transactions -> transaction -> cvv_result`

Also there seems that` transactions -> transaction -> details -> account -> billing_info -> vat_number` comes with a different name from the Recurly's API.

Related to: [Missing address and shipping address in invoice #240](https://github.com/killbilling/recurly-java-library/issues/240)

**Comment by aaron-suarez** [comment]
@jrg091 I'm about to implement these. I'm a little confused about your comment about `vat_number`. I just checked the response and I see the `<vat_number></vat_number>` tag coming from the API v2.15 under `transactions -> transaction -> details -> account -> billing_info`.

If you want to shed any light on what the difference is that you're seeing, I can see about fixing it.
