### ISSUE TITLE
Missing function in RecurlyClient to get Subscription Add-On's Usage

### ISSUE THREAD

**Issue by m-revetria** [killbilling/recurly-java-library#243]
Hi I'm using version `0.14.0` and seems that a function to get Subscription Add-On's usage is missing.

Reference: https://dev.recurly.com/docs/usage-record-object.

**Comment by aaron-suarez** [comment]
#239 Fixed this. Please upgrade to version 0.15.0 or later to take advantage of the `getSubscriptionUsages()` function.
