### ISSUE TITLE
Coupon's plans - Empty entries

### ISSUE THREAD

**Issue by jrg091** [killbilling/recurly-java-library#244]
I have a coupon assigned to all plans, in this case, when calling client's getCoupons, in the client's response I'm getting a list like: ["", "\n "] but in the API I get an empty array.

An example of the API response: 

```xml
<coupon href="https://remer.recurly.com/v2/coupons/code_01_test">
        <redemptions href="https://remer.recurly.com/v2/coupons/code_01_test/redemptions"/>
        <coupon_code>code_01_test</coupon_code>
        <name>coupon_01</name>
        <state>redeemable</state>
        ...
        <plan_codes type="array">
    </plan_codes>
        <a name="redeem" href="https://remer.recurly.com/v2/coupons/code_01_test/redeem" method="post"/>
    </coupon>
```

**Comment by aaron-suarez** [comment]
I think I was able to reproduce. I did the following:
```java
            Coupons coupons = client.getCoupons();
            System.out.println(coupons.get(0).getPlanCodes());
```
And it printed this out:
```
[,
    ]
```
I've never seen an array-like object printed like that before, this will be interesting to fix.

**Comment by aaron-suarez** [comment]
I'm going to let @bhelx handle this. I can't figure out what configuration of Jackson we need to be able to parse this correctly.
