### ISSUE TITLE
dueAt missing at dunning_event_notification

### ISSUE THREAD

**Issue by t-jarpis** [killbilling/recurly-java-library#245]
dueAt is not available. dueOn is there, but is not used for dunning event notifications

```
<new_dunning_event_notification>
<invoice>
   ...
    <due_at type="datetime">2016-10-26T16:00:12Z</due_at>
   ...
</invoice>
</new_dunning_event_notification>
```

**Comment by aaron-suarez** [comment]
Hi @t-jarpis! Thanks for your patience on this issue. The `due_at` tag is no longer going to be included in the `new_dunning_event_notification `, as it is replaced by the `due_on` tag. This change is related to the new [Credit Invoices](https://docs.recurly.com/docs/credit-invoices-release).

If your site is not already enabled with Credit Invoices, it will automatically change over November 1st. For this reason, we are not going to add the `dueAt` attribute to the `Invoice` class at this time.

Thanks for understanding. If you are still experiencing issues after enabling Credit Invoices on your site, please feel free to comment on this issue or open a new one. Thanks!
