### ISSUE TITLE
Unable to Update Shipping Address

### ISSUE THREAD

**Issue by MiellyEllen** [killbilling/recurly-java-library#253]
The RecurlyClient class does not provide a way to update the Shipping Address for an account. There is an HTTP API 
`PUT .../accounts/:account_code/shipping_addresses/:shipping_address_id` 
to update the shipping address, but not in Java library. As an alternative, I tried to change the shipping address with HTTP PUT .../accounts/{accountId}) and provided the the shipping address in the request payload, but I received
 `<error>
    <symbol>invalid_xml</symbol>
    <description>The provided XML was invalid.</description>
    <details>You can only nest shipping_addresses in your XML when creating a new record, not when updating.</details>
</error>`

The library does not appear to support the Delete Shipping Address feature either.
Is there an alternative that I'm missing?

**Comment by bhelx** [comment]
@MiellyEllen It might just be missing. I'll check. If that's the case, I'll create a PR adding it.

**Comment by MiellyEllen** [comment]
Thanks @bhelx! I modified the post because the Delete Shipping Address also appears to be missing.

**Comment by MiellyEllen** [comment]
oops

**Comment by bhelx** [comment]
@MiellyEllen no worries, I added all of them. PR incoming.

**Comment by MiellyEllen** [comment]
Hi @bhelx , Thanks for working on this. But found a Recurly wrinkle. Updating the shipping address on an account (Post or Put) does not update  the shipping address for the subscription -- which is where the tax is calculated. Recurly support told us to invoke the Update Subscription API and use the same xml payload documented in Create Subscription for  <shipping_address></shipping_address>-- this is undocumented. I tried it out (with postman) and it works. But, probably because it's not documented, this is not part of killbilling SubscriptionUpdate Class.  Before I submit a change request, I was curious if Killbilling adds features to it's library to invoke undocumented Recurly API features.

**Comment by bhelx** [comment]
@MiellyEllen If I remember correctly, the embedded shipping addresses (on a subscription for instance) are snapshots of the addresses.

I think in this case, since it's solving a reasonable use case, it's fine to add it to SubscriptionUpdate. I'll check to see if it's something we want to officially support and regression test on our end.
