### ISSUE TITLE
InvoiceCollection.getCreditInvoices not working

### ISSUE THREAD

**Issue by irphilli** [killbilling/recurly-java-library#259]
If credit invoices are enabled on a site, InvoiceCollection.getCreditInvoices is not working.

Seems like it should return an Invoices object, instead of List<Invoice>

**Comment by bhelx** [comment]
Hey @irphilli can you paste an error or some code demonstrating the problem?

**Comment by irphilli** [comment]
There really isn't an error message or anything, but let's say we have an active subscription, and we want to preview changing its value to 0 (effectively would generate a credit invoice)

```
SubscriptionUpdate subscriptionUpdate = new SubscriptionUpdate();
subscriptionUpdate.setUnitAmountInCents(0);
      
Subscription preview = getClient().updateSubscriptionPreview("uuid_of_some_subscription", subscriptionUpdate);
InvoiceCollection invoiceCollection = preview.getInvoiceCollection();

invoiceCollection.getCreditInvoices(); // returns null - should return a list of credit invoices
```

**Comment by bhelx** [comment]
@irphilli thanks, I'll take a look at it. I'm just now realizing we don't have an InvoiceCollection unit test. I'll get that going too.

**Comment by bhelx** [comment]
@irphilli I realized that the creditInvoices attribute didn't have an XmlElementWrapper annotation and that's why it wasn't parsing. I decided that adding that annotation would be more appropriate than returning Invoices in this case.

**Comment by bhelx** [comment]
Okay, turns out I was slightly wrong. Instead I added a `CreditInvoices` wrapper for this attribute.

**Comment by irphilli** [comment]
Thanks! I did something similar, but wasn't 100% sure if that was the right way to go. Looks good!
