### ISSUE TITLE
Update Subscription Shipping Address

### ISSUE THREAD

**Issue by MiellyEllen** [killbilling/recurly-java-library#260]
Updating the shipping address on an account (Post or Put) does not update the shipping address for the subscription – which is where the tax is calculated. Recurly support told us to invoke the Update Subscription API and use the same xml payload documented in Create Subscription for <shipping_address></shipping_address>-- this is undocumented. I tried it out (with postman) and it works. But, probably because it's not documented, this is not part of killbilling SubscriptionUpdate Class. Is it possible to implement this in the java library?

**Comment by bhelx** [comment]
@MiellyEllen Do you have a branch with the changes? If not, I can put this on my queue to implement.

**Comment by MiellyEllen** [comment]
Hi @bhelx , No I do not. Thanks for taking it up.

**Comment by MiellyEllen** [comment]
@bhelx , any word on when you can start this? We have to do a manual work around for customers who change their shipping address until this is in place.

**Comment by bhelx** [comment]
Hey @MiellyEllen, I'm going over my backlog this afternoon. Will see if I can move this to the front.

**Comment by bhelx** [comment]
@MiellyEllen just so i understand this before I start working on it, is this problem only on the `RecurlyClient#updateSubscription` method? If you could give me some code to demonstrate the problem, that would be great.

**Comment by bhelx** [comment]
@MiellyEllen I've started a a PR #264 . I still have a little work to do on it. Let me know if it's going in the right direction though. See the updated integration test to see how it's used.

**Comment by MiellyEllen** [comment]
@bhelx , Looks great but I should note that I have only tested the HTTP Update Subscription API where the whole shipping address is in the request payload. I then verified with the Recurly UI that a new Shipping address has been added.
I have not tried putting a shipping address id in the payload to see if that works too.

**Comment by bhelx** [comment]
Thanks for confirming for me! I haven't tested it yet, but I see support for it in the server.
