### ISSUE TITLE
Credit Invoices: Add support for original_invoices

### ISSUE THREAD

**Issue by irphilli** [killbilling/recurly-java-library#265]
With credit invoices enabled, the XML when you retrieve an invoice has an "original_invoices" element instead of "original_invoice".  Should add support for that element as well.

**Comment by cfrasineanu-intx** [comment]
We're gonna need this feature too. Any chance this will be released by mid-October.  According to Recurly:
`On November 1, 2018, Recurly will enable the Credit Invoices feature on all sites that have not yet enabled the feature.`
Thank you!
