### ISSUE TITLE
Accept-Language

### ISSUE THREAD

**Issue by t-jarpis** [killbilling/recurly-java-library#297]
Is seems not possible to add a custom header like Accept-Language to return translated error messages.

**Comment by aaron-suarez** [comment]
@t-jarpis, As you can see above, #298 adds a method to set the Accept-Language header. I have added the following note about thread safety to the PR description, and I wanted to make sure that you saw it before using this method.

NOTE: This is not thread safe. Consider the following situation:

```java
// in user 1's thread
client.setAcceptLanguage('de')
client.createSubscription()
```

```java
// in user 2's thread
client.setAcceptLanguage('en-US')
client.createSubscription()
```
These operations could interleave, such that `setAcceptLanguage()` gets called twice before the calls to `createSubscription()` are ever called. Meaning that if something went wrong with one of the requests, it would not be possible to guarantee that their error message would be in the correct language.

If your implementation takes advantage of threading (as most modern Java implementations do), you may experience problems by using this method in the above fashion. Please take all necessary caution to ensure that the client sets the correct language per request if you choose to use this method.
