### ISSUE TITLE
using purchase endpoint does not return subscription ID for purchasing a new subscription

### ISSUE THREAD

**Issue by cyu521** [killbilling/recurly-java-library#301]
the xml returned from recurly includes a url for subscription which has the subscription id in the url
```
 <?xml version="1.0" encoding="UTF-8"?>
<invoice_collection>
    <charge_invoice>
        <line_items type="array">
            <adjustment href="recurly.com/v2/adjustments/adjustmentId" type="charge">
                <account href="recurly.com/v2/accounts/accountId"/>
                <invoice href="recurly.com/v2/invoices/invoiceNumber"/>
                <subscription href="recurly.com/v2/subscriptions/subscriptionId"/>
```
if you can add the subscription url or parse it to get the ID and add it to the Adjustment class, that would allow purchase endpoint to return the subscription ID inside the chargeInvoice

**Comment by aaron-suarez** [comment]
@cyu521 This is a good point, it might be useful to get the subscription ID related to a particular adjustment. I'm going to see if I can find a way to make this happen.

**Comment by aaron-suarez** [comment]
The invoice also comes with a subscriptions tag:
```xml
<subscriptions href="https://recurly.com/v2/invoices/invoiceNumber/subscriptions"/>
```
Wouldn't it be better to just be able to get all the subscriptions for the invoice? 

I feel like calling a method on the RecurlyClient to get these subscriptions would be more useful than just getting the ID, but maybe there's something about your use case I'm not thinking of?

**Comment by cyu521** [comment]
@aaron-suarez 
In our case, I'm just looking to store the subscription ID. 
we are using this subscription ID to handle update and cancel to that subscription. 
we are only doing one subscription per purchase

**Comment by aaron-suarez** [comment]
Ok, thanks for clarifying. I'll see what I can get going with this
