### ISSUE TITLE
 PausedSubscriptionNotification has incorrect class name

### ISSUE THREAD

**Issue by cyu521** [killbilling/recurly-java-library#309]
Class `PausedSubscriptionNotification` has incorrect name, it should be `SubscriptionPausedNotification`
the xml root element is 
`@XmlRootElement(name = "subscription_paused_notification")`
Based on the Notification detect function
`CaseFormat.LOWER_UNDERSCORE.to(CaseFormat.UPPER_CAMEL, root)`
(root is subscription_paused_notification)

it will return `SubscriptionPausedNotification`
But this class type is not found when this code is processed
` Type.valueOf(CaseFormat.LOWER_UNDERSCORE.to(CaseFormat.UPPER_CAMEL, root)) `

It throws an IllegalArgumentException with the detailMessage
```
No enum constant com.ning.billing.recurly.model.push.Notification.Type.SubscriptionPausedNotification
```

**Comment by aaron-suarez** [comment]
Closed by #311
