### ISSUE TITLE
Update Maven Central with latest version

### ISSUE THREAD

**Issue by cyu521** [killbilling/recurly-java-library#314]
Hey Guys,

thank you so much for addressing my issues so quickly and getting them merge in.

If possible, please update maven central with the latest version so I can use the latest code!

This is blocking a few of my current tasks, if you can get this in as soon as possible, I would greatly appreciate it!

Thanks,
Chong

**Comment by aaron-suarez** [comment]
@pierre Would you please go ahead and cut a release when you get a chance?

**Comment by pierre** [comment]
Done!
