### ISSUE TITLE
infinite loop in BillingInfo.toString()

### ISSUE THREAD

**Issue by musketyr** [killbilling/recurly-java-library#326]
`Account` prints `billingInfo` inside `toString()` method but the billing info is trying to print the `account` as well causing an infinite loop and `StackOverflowException`.

**Comment by aaron-suarez** [comment]
Thanks for reporting the issue! We'll go ahead and take a look

**Comment by aaron-suarez** [comment]
@musketyr Can you please provide a code sample that shows the problem? When I do the following:
```java
client.open();
final Account account = client.getAccount("x");
System.out.println(account);
```
the `BillingInfo` info is all `null` values because the XML only contains a link to the billing info. It looks like this:
```
billingInfo=BillingInfo{account='null', type='null', firstName='null', lastName='null', company='null', address1='null', address2='null', city='null', state='null', zip='null', country='null', phone='null', vatNumber='null', ipAddress='null', ipAddressCountry='null', cardType='null', year=null, month=null, firstSix='null', lastFour='null', geoCode='null', updatedAt='null', externalHppType='null', gatewayToken='null', gatewayCode='null', amazonBillingAgreementId='null', amazonRegion='null'}
```
When I actually get the billing info for the account and set it, like so:
```java
client.open();
final Account account = client.getAccount("x");
final BillingInfo billingInfo = client.getBillingInfo(account.getAccountCode());
account.setBillingInfo(billingInfo);
System.out.println(account);
```
The billing info has some values now, but it doesn't create an infinite loop in the account because the only value in the Account object is the link back to the account:
```
billingInfo=BillingInfo{account='Account{address=null, href=https://aaron-dev.recurly.com/v2/accounts/x, adjustments=null, invoices=null, subscriptions=null, transactions=null, accountCode='x', state='null', username='null', email='null', ccEmails='null', firstName='null', lastName='null', companyName='null', acceptLanguage='null', hostedLoginToken='null', createdAt=null, updatedAt=null, billingInfo=null, taxExempt=null, exemptionCertificate='null', shippingAddresses=null, customFields=null, hasLiveSubscription=null, hasActiveSubscription=null, hasFutureSubscription=null, hasCanceledSubscription=null, hasPastDueInvoice=null, hasPausedSubscription=null, vatNumber=null, accountAcquisition=null, preferredLocale=null}', type='credit_card', firstName='John', lastName='Jacob Jinglheimer Schmidt', company='null', address1='123 main st', address2='null', city='testily', state='CA', zip='95312', country='US', phone='213-555-5555', vatNumber='54321', ipAddress='null', ipAddressCountry='null', cardType='Visa', year=2020, month=12, firstSix='411111', lastFour='1111', geoCode='null', updatedAt='2019-02-25T14:59:41.000-06:00', externalHppType='null', gatewayToken='null', gatewayCode='null', amazonBillingAgreementId='null', amazonRegion='null'}
```

I'm curious whether you're using the library in a way that it wasn't necessarily intended to be used. But either way, in order to fix the problem, I'll need to be able to reproduce it, so please provide a code sample. Thanks!

**Comment by musketyr** [comment]
the problem can happen when you create new account and billing info

```
final Account account = new Account();
// set account properties
final BillingInfo info = new BillingInfo();
// set billing info properties

account.setBillingInfo(info);
info.setAccount(account);

// System.out.println(account); will now fail

client.createAccount(account);

// do some billing info adjustments
client.createOrUpdateBillingInfo(info)
```

Typical example when you need to create billing info is when you are using `tokenId` for the first time.

**Comment by bhelx** [comment]
@musketyr Possibly unrelated, but I don't think you need the line `info.setAccount(account);`. I believe `account.setBillingInfo(info);` should be sufficient.

**Comment by aaron-suarez** [comment]
When you create an account with BillingInfo included, the account should include the billing info properties that you made in the `createAccount` request, and it should show up on the Recurly app website. The only time you need to use `createOrUpdateBillingInfo` is if you have subsequent changes to the billing info and need to update it, or if you created an account before collecting the billing info and then need to create billing info for that account.

That being said, I'll still see if I can do something about the infinite loop in the toString() method just in case someone else runs into this.
