### ISSUE TITLE
Invoice model, line 165

### ISSUE THREAD

**Issue by KoenDG** [killbilling/recurly-java-library#33]
https://github.com/killbilling/recurly-java-library/blob/master/src/main/java/com/ning/billing/recurly/model/Invoice.java#L165

Never going to get assigned. Was this done for a reason?

**Comment by bhelx** [comment]
I was not able to reproduce this. I'm assuming it's fixed. Please re-open if there still seems to be a problem here.

Also, NB: when you reference line numbers they get out of date pretty quick. You can push the `y` key which will switch you to a commit specific view. You can then click on the line number to get a permanent link. Example:

https://github.com/killbilling/recurly-java-library/blob/660bf5a29ab61a05ddfdc87d8255c196b3439106/src/main/java/com/ning/billing/recurly/model/Invoice.java#L287
