### ISSUE TITLE
Get account transactions: subscription is always null

### ISSUE THREAD

**Issue by demetrio812** [killbilling/recurly-java-library#330]
Hello,
everytime we get the list of the transactions, the subscription field is null.

We checked the xml returned by Recurly and there is no subscription field, there is a subscriptions field (plural) that looks like this:

    <subscriptions href="https://name.recurly.com/v2/transactions/<transaction_uuid>/subscriptions"/>

And that call will return an array of subscriptions connected to the transaction.

So I think (and correct me if I'm wrong) that the "subscription"(singular) is something that can be removed.

Let me know if I'm missing something

Thanks,
Dem

**Comment by aaron-suarez** [comment]
It looks like API versions 2.0-2.7 had `subscription`, then 2.8 had both `subscription` and `subscriptions`, then 2.9+ just has `subscriptions`. I think it's just a relic of an earlier API version. If you'd like to do a PR to remove it, I'll be happy to review and merge

**Comment by demetrio812** [comment]
Hello @aaron-suarez , just created a PR

Let me know

Cheers,
Dem

**Comment by aaron-suarez** [comment]
#331 will close this out

**Comment by aaron-suarez** [comment]
Apparently those are some magic words

**Comment by aaron-suarez** [comment]
Closed #331 due to inactivity. We'll leave this issue open until someone has a chance to make the required change with the suggestions listed in the closed PR.

**Comment by joannasese** [comment]
Hi @aaron-suarez and @demetrio812. https://github.com/killbilling/recurly-java-library/pull/374 closes this out. Thanks for contributing!
