### ISSUE TITLE
Can't set exempt flag when creating a Plan

### ISSUE THREAD

**Issue by mzouitni** [killbilling/recurly-java-library#334]
When I try to create a Plan I noticed that I cannot set the taxExempt flag, the Plan doesn't have this attribute. Any possibility to add it in?

**Comment by bhelx** [comment]
Yes, I'll put this on our list for Monday. I'll make sure we aren't missing any other attributes on that class as well.

**Comment by aaron-suarez** [comment]
Closed in #336
