### ISSUE TITLE
host validation in 0.25 version

### ISSUE THREAD

**Issue by mzouitni** [killbilling/recurly-java-library#335]
Our local development makes recurly calls against a mocked server, when we upgraded to 0.25 we noticed that the code does host validation. Is it possible to add an option to bypass the validation in the scenario where we are testing?

**Comment by bhelx** [comment]
We're open to ideas and PRs, but it's a security concern so we should be careful about how it gets to the public interface. Our primary concern is people accidentally disabling the hostname whitelisting in production.

**Comment by mzouitni** [comment]
What about skipping this validation if the site is on dev mode and impose the check of the recurly site is in prod mode ?

**Comment by bhelx** [comment]
I don't think there would be a way to know that without calling the server. Still open to doing this in some way, it just has to be pretty painfully obvious to the programmer that what you are doing is disabling SSRF protection.

**Comment by mzouitni** [comment]
I don’t think it is the best solution but I agree with the concern.

**Comment by nwarz** [comment]
+1 for an option to bypass hostname validation, but I don't know the best way to emphasize that it should be for testing only.

**Comment by x80486** [comment]
You should be able to present this as _configuration_, with some defaults — what you have now; but there must be a way to override the value(s) as needed.

Pretty much all libraries that make outbound HTTP calls provide a way for you to change that, falling back to some defaults. I can think of `EndpointConfiguration` for AWS libs, for instance.

**Comment by bhelx** [comment]
I'm still open to this being configurable if anyone has a suggestion for the interface. My primary concern is that the programmer is able to accidentally disable SSRF. That could be mitigated if we add some validation that this list cannot be empty: https://github.com/killbilling/recurly-java-library/blob/master/src/main/java/com/ning/billing/recurly/RecurlyClient.java#L125
As long as the programmer has to provide a whitelist of specific valid domains, I feel confident from a security perspective. We also want to warn the programmer that they are doing something unusual if possible. This should never be used in production.

**Comment by aaron-suarez** [comment]
Should we just add a public setter method, but also a check for `if ( (validHosts == null) || (! validHosts.Any()) )` in this method?

https://github.com/killbilling/recurly-java-library/blob/5e05eedd91885a51e1aa8293bd41139d082cf7f4/src/main/java/com/ning/billing/recurly/RecurlyClient.java#L2343-L2353

**Comment by bhelx** [comment]
I'm okay with a public method to add another valid host. I think we only need to validate validHosts when it changes and probably not every time we call `validateHost`. I also thing we should log some kind of message warning the programmer. Open to other ways to do it if there is an argument for security.

Once again, want to point out that we're okay with configuring this check, but not allowing anyone to disable it. If a web user is able to find a bug and manipulate the client to point at a server they control (e.g. something like requestbin) they will have your API key. So if a programmer wants to change this value, they should be required to enumerate which servers are safe to call.

**Comment by aaron-suarez** [comment]
Closing this out due to inactivity. If anyone would like to open a PR adding some code (probably not in `validateHost`) that will allow the programmer to add additional valid hosts, we'll be happy to review and merge, assuming it meets our security requirements. Thanks!
