### ISSUE TITLE
Missing tax related fields on Adjustment object

### ISSUE THREAD

**Issue by surajmaher** [killbilling/recurly-java-library#339]
It looks that following fields which are present in other client libraries are missing in Java Adjustment object.

Following is the link - https://dev.recurly.com/docs/adjustment-object.

Missing fields
- tax_code
- tax_rate
- tax_type
- tax_region

```
		<dependency>
			<groupId>com.ning.billing</groupId>
			<artifactId>recurly-java-library</artifactId>
			<version>0.24.0</version>
		</dependency>
```

We currently only need tax_code field but adding other missing fields as well in case they amount to same work.

**Comment by aaron-suarez** [comment]
@surajmaher Thanks for pointing out these missing fields! We'll get a fix in for these as well as #338 soon
