### ISSUE TITLE
Missing fields in SubscriptionUpdate model

### ISSUE THREAD

**Issue by pennstatephil** [killbilling/recurly-java-library#341]
**Describe the bug**

As #35 said (it was closed without being fixed) there are multiple missing fields for updating subscriptions. Full list at https://dev.recurly.com/docs/update-subscription

**To Reproduce**

Attempt to use a field that isn't in the model, it's not there.

**Expected behavior**

All fields are available for use.

**Your Environment**

Latest version of library
Java 1.8

**Comment by aaron-suarez** [comment]
We'll take a look, thanks for reporting this
