### ISSUE TITLE
Malformed XML mapped when adding multiple coupon codes

### ISSUE THREAD

**Issue by benj1502** [killbilling/recurly-java-library#349]
Hello,

**Describe the bug**

The issue I'm facing is that: whenever I try to call the "create subscription" or "preview subsription" with a subscription that we have set a list of coupons into always return the XML malformed error. It complains that tag <coupon_codes> should contain only sub tag <coupon_code> (code without 's').
Recurly tech guy provided me the malformed part:

```
<coupon_codes>   
     <coupon_codes>dungdiscount</coupon_codes>    
     <coupon_codes>ben_code_10</coupon_codes>
</coupon_codes>
```

which is supposed to be below instead:
```
<coupon_codes>   
     <coupon_code>dungdiscount</coupon_code>    
     <coupon_code>ben_code_10</coupon_code>
</coupon_codes>
```

**To Reproduce**
 
```      // Apply multiple coupon at the time of subscription creation
            List<String> couponCodes = new ArrayList<String>();
            couponCodes.add("dungdiscount");
            couponCodes.add("ben_code_10");
            subscriptionData.setCouponCodes(couponCodes);
            final Subscription subscriptionPreview = recurlyClient.previewSubscription(subscriptionData);
```

https://v2uploads.zopim.io/v/x/3/vx3xUhLgBy3QROz61Nhq6O0TdxoYyN04/385fdfd40a31e30d8119e778b74d8e387a75b586.png

** Possible root cause **
Found out something that  might be the root cause, its this class in the java client library: 

`com.ning.billing.recurly.model.Subscription`

    
``` 
    @XmlList
    @XmlElementWrapper(name = "coupon_codes”) —> This line of code made the tag <coupon_codes> reappear as subtags of that same tag.
    private List<String> couponCodes;
```

Changing it below will make the XML to be formatted as expected:
   
 ``` 
    @XmlElementWrapper(name = "coupon_codes")
    @XmlElement(name="coupon_code”) —> this line of code will allow the tag <coupon_code> appears as sub tag of <coupon_codes>
    private List<String> couponCodes;
```

**Expected behavior**
XML is formed correctly and the API returned a subscription object with corresponding data.
<coupon_codes>   
     <coupon_code>dungdiscount</coupon_code>    
     <coupon_code>ben_code_10</coupon_code>
</coupon_codes>

**Your Environment**

- Which version of this library are you using?
recurly-java-library: 0.28.0
RECURLY_API_VERSION=2.21

**Comment by aaron-suarez** [comment]
Thank you for your report! We'll take a look and get this resolved

**Comment by aaron-suarez** [comment]
@benj1502 Is this a blocker for you? If so, we'll go ahead and release this fix early, otherwise I believe the next API version is coming out at the end of August so this would end up going out with that release.

**Comment by benj1502** [comment]
Hello Aaron, thanks for checking in. This unfortunately is a blocker for us, we're supposed to release our related implementation by end of this week... So if possible could you guys release this fix early?

Thank you,
Ben

**Comment by aaron-suarez** [comment]
@pierre When you get a chance, could you go ahead and cut a release to unblock @benj1502? Thank you so much!

**Comment by pierre** [comment]
0.29.0 released!

**Comment by aaron-suarez** [comment]
Thanks Pierre!

**Comment by benj1502** [comment]
Thank you for the effort, we'll check it out!!!

Cheers!
