### ISSUE TITLE
Missing the previewInvoice API call

### ISSUE THREAD

**Issue by benj1502** [killbilling/recurly-java-library#353]
Hello, it looks like you guys don't have a method created in RecurlyClient.java in order to make a call to the Preview Invoice endpoint below. 
https://:subdomain.recurly.com/v2/accounts/:account_code/invoices/preview
Would it be possible if you can implement one? We're actually in a critical situation right now realizing we don't have the method needed.

Thank you very much!
Ben

**Comment by bhelx** [comment]
@benj1502 I believe this is implemented as `Client#previewInvoice`. You might also want to look at `Client#previewPurchase` as well. I'd recommend you use previewPurchase over previewInvoice unless you have a reason not to:

https://github.com/recurly/recurly-client-java/blob/d0583c305222570c7e141f2e7738eeef3505fd4e/src/main/java/com/recurly/v3/Client.java#L436
https://github.com/recurly/recurly-client-java/blob/d0583c305222570c7e141f2e7738eeef3505fd4e/src/main/java/com/recurly/v3/Client.java#L1768

**Comment by bhelx** [comment]
@benj1502 Apologies, I just linked information from the wrong library. I believe it may not be implemented because we want to encourage people to use `previewPurchase` instead:

https://github.com/killbilling/recurly-java-library/blob/17c419aad79e8060bde32516e6ac4dc8a9f72618/src/main/java/com/ning/billing/recurly/RecurlyClient.java#L1915

Does that work for your use case?

**Comment by benj1502** [comment]
Hi @bhelx , unfortunately it does not, the reason why we looked for that "preview invoice" method was because "previewPurchase" does not work for our scenario...

**Comment by bhelx** [comment]
@benj1502 could you explain your use case? I'm curious to know. Happy to get the `previewInvoice` method in here regardless.

**Comment by benj1502** [comment]
Our scenario is that we allow users to subscribe to a plan, which has a free trial period, and we have a requirement to allow user entering the promo code, we need to display the final price after being discounted upfront so that users can see before they actually hit the Subscribe button. We tried previewSubscription, previewPurchase, they don’t work because user has not actually been charged yet so those 2 APIs can’t return a discounted price, it returned $0 instead.

There’s a recommendation from another Recurly reps to instruct us to create another "workaround" plan with no trial period, we can use the previewPurchase/previewSubscription with that plan, it works. 
BUT, the problem is, there are some existed coupon codes that have already been configured to only be eligible for the plan with trial period (actual plan, not the workaround plan with no trial period), those coupons have to still be valid for new users —> When new users subscribe with a valid promo code entered and we use previewPurchase/previewSubscription to attempt to get the discounted price, it returns an error saying the coupon code is not valid because it is being applied to a non-eligible plan,  which technically true, because the coupon created before we have the no-free trial plan, so it is invalid for this plan.

So we thought that we should leverage the preview invoice endpoint to get the to-be-charged price out of user’s subscription. We managed to be able to call the previewInvoice endpoint successfully, but it turns out that the endpoint does not provide what we wanted as well. It always return error 422.

**Comment by joannasese** [comment]
Hi @benj1502. Picking this up. Have you been able to use a workaround or is `previewInvoice` something you still need?

**Comment by joannasese** [comment]
Hi @benj1502. I'm going to go ahead and close this issue. If it still needs our attention, please let us know.

**Comment by benj1502** [comment]
Sorry @joannasese I lost track of this thread. We were able to workaround the problem.

Thank you, stay safe.
