### ISSUE TITLE
Key agnostic client interface

### ISSUE THREAD

**Issue by slisaasquatch** [killbilling/recurly-java-library#355]
In my use case, I need the ability to pass in a different API key per request. I actually already went ahead and implemented it myself, along with some other cleanups.

Here's the diff: https://github.com/killbilling/recurly-java-library/compare/master...saasquatch:key-agnostic-io, and I want to get some feedback before I create a pull request, if that's something you guys are interested in.

Here are some notable changes I made:
1. It includes a `KeyAgnosticRecurlyClient`, which is just a wrapper for `RecurlyClient` that allows an apiKey to be passed in for each request. I also made some changes on `RecurlyClient` to support this.
2. I replaced the ning AsyncHttpClient with Apache HttpClient 4.5, because the version of AsyncHttpClient is pretty out-of-date, and it's being used in a blocking way. Also, it's causing some build conflicts with my project. I have tried to maintain the existing behavior of AsyncHttpClient with Apache HttpClient, so the switch should be seamless. Plus, lots of people are already using Apache HttpClient (including myself), so it's one less dependency to import. And since Apache HttpClient is blocking and not callback based, Exception handling becomes a lot easier.
3. I implemented the restoreCoupon API, which is an API I need in my project.
4. I replaced `DataTypeConverter` with Guava's `BaseEncoding.base64()`, because the project already depends on Guava, and `DataTypeConverter` can potentially cause problems with Java 9+.
5. I created a base Exception class called `RecurlyException`, which all the other Exception types in this library extends.
6. There are some other trivial cleanups like using the Guava `Charsets` and `HttpHeaders` constants.

Thanks!

**Comment by slisaasquatch** [comment]
So a little update for my fork. I created another branch with a different approach. Instead of having a complete separate class `KeyAgnosticRecurlyClient`, I instead added the ability to add your own headers to `QueryParams`, which can be used to override API keys. I think this approach should be more maintainable. Here's the diff: https://github.com/killbilling/recurly-java-library/compare/master...saasquatch:key-agnostic-io2
Please let me know if you guys have any suggestions.

**Comment by slisaasquatch** [comment]
Oh and this can also fix https://github.com/killbilling/recurly-java-library/issues/363

**Comment by pierre** [comment]
@killbilling/recurly FWIW, in Kill Bill's Java client, we took the approach of adding an extra `RequestOptions` parameter to each API call. See [createAccount](https://github.com/killbill/killbill-client-java/blob/42ebdf514e09bc51a68c9b6d69904915f8db481e/src/main/java/org/killbill/billing/client/api/gen/AccountApi.java#L162) for instance. This [object](https://github.com/killbill/killbill-client-java/blob/master/src/main/java/org/killbill/billing/client/RequestOptions.java) lets you control headers, authentication keys, etc.  on a per request basis.

This could be a viable approach for this library as well (and I believe very much aligned to what @slisaasquatch is describing above)?

@slisaasquatch Regarding your fork, thank you for these pointers. Unfortunately, the changes are quite extensive in both of your branches and would be too difficult for us to review in details. We can still keep this ticket open to track the the _ability to to pass in a different API key per request_ feature.
