### ISSUE TITLE
Ning recurly failed to parse Recurly error 

### ISSUE THREAD

**Issue by mrbkiter** [killbilling/recurly-java-library#359]
When calling Recurly APIs using this lib, I sometimes got this error:

https://***.recurly.com:443/v2/accounts/localhost.vinceredev.com/billing_info

`<?xml version="1.0" encoding="UTF-8"?>
<error>
<symbol>simultaneous_request</symbol>
<description>A billing info change for account localhost.vinceredev.com is already in progress</description>
</error>`

Unfortunately this lib is unable to parse this error message correctly. I got following exception:

com.ning.billing.recurly.TransactionErrorException: Errors{transactionError=null, transaction=null, recurlyErrors=null}
at com.ning.billing.recurly.RecurlyClient.callRecurlyXmlContent(RecurlyClient.java:2292)
at com.ning.billing.recurly.RecurlyClient.callRecurlySafeXmlContent(RecurlyClient.java:2235)
at com.ning.billing.recurly.RecurlyClient.doPUT(RecurlyClient.java:2190)
at com.ning.billing.recurly.RecurlyClient.createOrUpdateBillingInfo(RecurlyClient.java:782)

May you help check again? It seems RecurlyErrors does not cover this kind of exception.

**Comment by bhelx** [comment]
Thanks @mrbkiter 

We are investigating. Could you let us know which version of the java library you are using? Is the error unexpected in general, just the failure to parse the error, or both?

**Comment by mrbkiter** [comment]
Hi @bhelx 

Im using version 0.29.0. My reproduce steps are: 

1. Using recurly.js latest version, I created a processing transaction (I got transaction token)
2. Recurly server return 3d secured action token. I don't use it but just reload the page to reinitialize another transaction. 
3. Repeat step 1 again, you will get exception above from recurly server. 

From my perspective, this issue  possibly happen because of the 3d secure process being applied for EU banks as required as of middle of September. When a transaction is not complete, new one would be prevented.

**Comment by mrbkiter** [comment]
More info, the Error status code: 422 for this issue

**Comment by mrbkiter** [comment]
One example I got today:

Recurly error whilst calling: https://***.recurly.com:443/v2/subscriptions
<?xml version="1.0" encoding="UTF-8"?>
<error>
<symbol>token_invalid</symbol>
<description>Token (billing_info.token_id) is either invalid or expired</description>
</error>

**Comment by williamho** [comment]
I think this is the same underlying issue as https://github.com/killbilling/recurly-java-library/issues/354 and would be fixed by this PR: https://github.com/killbilling/recurly-java-library/pull/360.

Currently the library is expecting all 422 errors to be transaction errors (of the form `<errors>...</errors>`) when the reality is that sometimes it can be a single error (`<error>...</error>`)

**Comment by bhelx** [comment]
Thanks @williamho. Closed with https://github.com/killbilling/recurly-java-library/pull/360
