### ISSUE TITLE
Add credit_payments field to Invoice

### ISSUE THREAD

**Issue by jan-ee** [killbilling/recurly-java-library#361]
Hi! I was wondering if it would be possible to get the "credit_payments" field added to the Invoice.java object.

```
   @XmlElementWrapper(name = "credit_payments")
   @XmlElement(name = "credit_payment")
   private CreditPayments creditPayments;
```

Thank you!

Jan

**Comment by joannasese** [comment]
Hi @jan-ee. Missed this one! Sorry about that. Just wanted to let you know there are eyes on it.

**Comment by joannasese** [comment]
Hi @jan-ee. https://github.com/killbilling/recurly-java-library/pull/371 closes this out. Thanks for your contribution!

**Comment by jan-ee** [comment]
Thank you!
