### ISSUE TITLE
Missing header from generateUniqueCodes  response

### ISSUE THREAD

**Issue by cyu521** [killbilling/recurly-java-library#365]
**Describe the bug**
When calling generate unique codes, i expected to get back the cursor of where the coupon code is generated. Currently, this function is a void function.

for this endpoint
https://dev.recurly.com/docs/generate-unique-codes

Based on the description, there is a cursor in the location header.

```
The response will include the location of the unique codes as link in the header:

https://your-subdomain.recurly.com/v2/coupons/savemore/unique_coupon_codes?cursor=1792526747654056328&per_page=200
```

Currently the function is a void type, expected behavior is to return an object that contains the cursor so i can know where the unique code is generated.

**To Reproduce**

Call the generateUniqueCodes function
Nothing is returned (void function)

**Expected behavior**

An object that contains the cursor 

**Your Environment**

- Which version of this library are you using?
0.27.0

- Which version of java are you using?
java 11

**Comment by cyu521** [comment]
Currently this is creating a race condition in our production environment.
 
We are sending two users the same coupon code if the coupons are generated at the same time.
Which happens since a third party is running a batch job to ask us to generate coupons.
Getting the cursor would help us resolve this issue by allowing us to fetch the correct coupon code per request

**Comment by joannasese** [comment]
Hi @cyu521. 

> Currently this is creating a race condition in our production environment. We are sending two users the same coupon code if the coupons are generated at the same time.

So we can identify if this is a bug, can you help us reproduce this?

**Comment by cyu521** [comment]
To generate a new coupon, i was calling

`generateUniqueCodes(couponPrefix, coupon)`
then to get that new coupon that i generated,
```
    val param = QueryParams().also {
            it.setSort(QueryParams.Sort.CREATED_AT)
            it.setOrder(QueryParams.Order.DESC)
        }
        val newCoupon = recurlyClient.getUniqueCouponCodes(couponPrefix, param).firstOrNull {
            it.state == REDEEMABLE_STATE
        } 
```
I expect the first redeemable state to be where the coupon list is sorted by created at, to be the one i created.

I am getting a race condition because i called this endpoint within milliseconds apart, they both generated a new coupon, but because they're so close apart, on the fetch, they both fetched the same first coupon.

The current API Doc have this header in the returned response. but the java lib does not return anything

**Comment by joannasese** [comment]
```

**Comment by joannasese** [comment]
Would something like this address your issue, where `generateUniqueCodes()` returns accessible values?

```
Coupon genCouponData = new Coupon();
genCouponData.setNumberOfUniqueCodes(1);
Coupons coupons = recurlyClient.generateUniqueCodes(couponCode, genCouponData);
Coupon uniqueCode = coupons.get(0);
```

**Comment by cyu521** [comment]
Yes! Something like that would be great.

Another solution is to just return the cursor and I can set it as query param for the get unique coupon function

**Comment by joannasese** [comment]
Hi @cyu521.

Please take a look at [this PR](https://github.com/killbilling/recurly-java-library/pull/366/files). If these changes work for you, you should be able to access coupon codes.

```
Coupon genCouponData = new Coupon();
genCouponData.setNumberOfUniqueCodes(3);
Coupons coupons = recurlyClient.generateUniqueCodes(coupon.getCouponCode(), genCouponData);
Coupon c = coupons.get(0);
System.out.println("Coupon c " + c.toString());
```

**Comment by cyu521** [comment]
hi @joannasese ! 

the changes looks good! 

thanks!

**Comment by joannasese** [comment]
@cyu521 Excellent! I'll close this issue. Please reach out if you need assistance in the future.
