### ISSUE TITLE
Checking in on release cadence

### ISSUE THREAD

**Issue by hijklmno** [killbilling/recurly-java-library#375]
Hello Recurly Dev Team,

Thank you for your time. 

I'm following up on PR #367. Would it be possible to get a maven release out soon? We are looking to integrate ACH as a payment method for our customers.

Thanks again!

**Comment by pierre** [comment]
0.33.0 has been released.

**Comment by joannasese** [comment]
Thanks @pierre. 

@hijklmno you should be good to go.

**Comment by hijklmno** [comment]
Thank you @pierre and @joannasese!
