### ISSUE TITLE
GiftCard model: gifterAccountCode, recipientAccountCode, invoiceNumber missing

### ISSUE THREAD

**Issue by demetrio812** [killbilling/recurly-java-library#376]
Hello,
I've noticed the following fields are missing from the GiftCard model: 
- gifterAccountCode
- recipientAccountCode
- invoiceNumber missing

I've added them in a fork: 

https://github.com/demetrio812/recurly-java-library/commit/7e1ee6310bcb736d2a629a4b9d44c7846c934b99

Let me know if and how I can help

Thanks
Dem

**Comment by joannasese** [comment]
Hi @demetrio812.

Thanks for reporting! We'll take a look and get back to you soon.

**Comment by joannasese** [comment]
Hi @demetrio812. Thanks again for reporting. Your contributions will be included in the next release.
