### ISSUE TITLE
Infinite Recursion

### ISSUE THREAD

**Issue by enda-odonohoe** [killbilling/recurly-java-library#397]
**Describe the bug**

Infinite recursion in call ResponseMetaData.getStatusCode()

**Comment by joannasese** [comment]
Hi @enda-odonohoe. Thanks for reporting. We'll investigate. Which version of the library are you using?

**Comment by enda-odonohoe** [comment]
I forked from master, so its in the current version.

**Comment by slisaasquatch** [comment]
Fixed here https://github.com/killbilling/recurly-java-library/pull/400

**Comment by joannasese** [comment]
Hi @enda-odonohoe. https://github.com/killbilling/recurly-java-library/pull/400 addresses the issue and will included in an upcoming release to be cut by end of month.
