### ISSUE TITLE
PUT request on convertTrial never works properly

### ISSUE THREAD

**Issue by wnadglowski** [killbilling/recurly-java-library#398]
ConvertTrial in RecurlyClient never works properly - Recurly API always returns status 411 Length required. The request is missing "Content-Length" header. It should always be present, even if the request body is empty.

**Comment by slisaasquatch** [comment]
This will be fixed in the next version. See here https://github.com/killbilling/recurly-java-library/pull/394

**Comment by joannasese** [comment]
@wnadglowski we'll soon be cutting a release that includes the Apache upgrade referenced in https://github.com/killbilling/recurly-java-library/pull/394. I'll close out this ticket when the new version is out.

**Comment by joannasese** [comment]
Hi @wnadglowski just letting you know that we've cut a release, so I'm closing out this ticket.
