### ISSUE TITLE
Encoding of strings read from Recurly is sensitive to current locale

### ISSUE THREAD

**Issue by glasser** [killbilling/recurly-java-library#403]
**Describe the bug**

We have a customer whose company name is, say, `UTF8 ț Test`.
When we read this value via `RecurlyClient.getAccount("foo").getCompanyName()`, the name gets converted to `UTF8 �� Test`, if our program is running in a locale like `LC_ALL=C` on Linux. 

Setting `LC_ALL=C.UTF-8` or using `-Dfile.encoding=UTF-8` fixes this, but since Recurly is always sending UTF-8, it would be great if you don't have to carefully run your app in this locale.

I believe the bug comes from this code in RecurlyClient.java:

```
    private String convertStreamToString(final java.io.InputStream is) {
        try {
            return new Scanner(is).useDelimiter("\\A").next();
        } catch (final NoSuchElementException e) {
            return "";
        }
    }
```

This Scanner constructor uses the platform charset instead of specifying UTF-8. Switching to the constructor that specifies the charset should help.

**Your Environment**

- Which version of this library are you using?

0.34.0

- Which version of java are you using?

zulu8.46.0.19-ca-jdk8.0.252-linux_x64

**Comment by glasser** [comment]
My suspicion is that this is fixed on master by @joannasese 's #390 which replaces the entire convertStreamToString function with convertEntityToString which does specify a charset explicitly. However, this PR has not yet been released. Are you able to do a new release which contains this PR?

**Comment by joannasese** [comment]
Hi @glasser. Thanks for reporting. I agree with your suspicions, but can't take the credit for #390. That was all @slisaasquatch.

We have a release scheduled for this week. I'll close out this issue when the release is cut. If you still encounter issues, please go ahead and reopen the ticket.

**Comment by glasser** [comment]
Oops, sorry for the misattribution @slisaasquatch!

I would be happy to help you test #390 before release if you're able to make some sort of pre-release that I can load with the normal Gradle/maven mechanisms, FWIW.

**Comment by joannasese** [comment]
Hi @glasser. The release has been cut, so I'm closing out this ticket.
