### ISSUE TITLE
Null Pointer Exception in toString() of BillingInfo

### ISSUE THREAD

**Issue by Shivani-SinghDeo** [killbilling/recurly-java-library#405]
**BillingInfo** class method **toString()** is giving Null Pointer Exception as the account is not null but the **account.getBillingInfo()** is coming as null while updating the billing info of an account

BillingInfo updatedBillingInfo = recurlyClient.createOrUpdateBillingInfo(accountCode, billingInfo);

Pass the account code and the billing info with the token. When printing updatedBillingInfo it would give NPE.

Code giving NPE : 

`if (account != null && account.getBillingInfo().equals(this)) {
            sb.append("{account='").append(account.getAccountCode()).append('\'');
        }`

**Environment**

Library Version - 0.27.0
Java Version - Java 8

**Comment by Shivani-SinghDeo** [comment]
@joannasese Adding this code worked 

`Account account = getAccount();
		if (account != null && account.getBillingInfo() != null && this.getHref() != null
				&& this.getHref().equals(account.getBillingInfo().getHref())) {
			sb.append("{account='").append(account.getAccountCode()).append('\'');
		} else {
			sb.append("{account='").append(account).append('\'');
		}`

**Comment by Shivani-SinghDeo** [comment]
@joannasese Can you please review this change - https://github.com/killbilling/recurly-java-library/pull/406

**Comment by joannasese** [comment]
Hi @Shivani-SinghDeo. Thanks for the contribution! I was able to reproduce the error and am reviewing your PR.
