### ISSUE TITLE
Names with foreign characters break calls to recurly

### ISSUE THREAD

**Issue by maxkremer** [killbilling/recurly-java-library#41]
Text submitted with the Recurly client containing text such as Björn fail due to improper char encoding

**Comment by glasser** [comment]
Worth noting that we are seeing an issue where reading from Recurly corrupts Unicode characters. Making sure we run in a locale like `LC_ALL=C.UTF-8` fixes it, but it would be great if this library was Unicode-compatible by default not depending on locale!
