### ISSUE TITLE
[Feature Request] Support Authorization Cancellation

### ISSUE THREAD

**Issue by zocomd** [killbilling/recurly-java-library#419]
Hi, 

Can we please add support for Authorization Cancellation? It should map to [v2/purchases/cancel API](https://docs.recurly.com/docs/auth-and-capture#section-auth-and-capture). I see we already support [authorizePurchase()](https://t.ly/LQlU). If we already have a way to cancel an authorization, please let me know too. Thanks in advance.

_Warning_: Github issues are not an official support channel for Recurly. If you have an urgent request we suggest you contact us through an official channel: support@recurly.com or https://recurly.zendesk.com

**Comment by joannasese** [comment]
Hi @zocomd. Apologies for missing this! We'll see what we can do about adding this endpoint. I'll keep this issue open for now.

**Comment by joannasese** [comment]
Hi @zocomd. We've added support for capture and cancel authorizations. These updates will be included in the next release.
