### ISSUE TITLE
Setup travis for PR

### ISSUE THREAD

**Issue by pierre** [killbilling/recurly-java-library#71]
Integration tests could be run against a sandbox automatically.

**Comment by bhelx** [comment]
This can be closed due to https://github.com/killbilling/recurly-java-library/pull/83

**Comment by bhelx** [comment]
I'm going to look into this but I'm unsure the best way to get the integration tests running in Travis. Perhaps I can create a sandbox site and somehow set the keys only in Travis. I'd also need to look and see if api rate limiting will affect this.

**Comment by pierre** [comment]
You can set private (*secure*) environment variables in Travis (I can set it up if you PM me the secret API key): you can then override the `script` entry in the `travis.yml` to pass them on the command line (`-D...`).

BTW, it would be great if we could have a sandbox with enterprise features enabled, so we could run the `enterprise` suite as well.

**Comment by bhelx** [comment]
Yeah, good idea. I can setup whatever kind of sandbox and add all the feature flags to it. I noticed the integration tests don't work when you have line item refunds enabled but that's something I can fix later. Let me talk to some people about the rate limiting thing. I think it should be fine though.

**Comment by pierre** [comment]
Any update on getting a sandbox just for Travis? Since we have lots of changes these days, this could be  quite useful.

**Comment by bhelx** [comment]
@pierre this is on my task list for this week. I think it should be pretty quick. Expect a PR in the next couple days.

**Comment by bhelx** [comment]
Closed with https://github.com/killbilling/recurly-java-library/pull/108
