### ISSUE TITLE
guava defined as provided dependency

### ISSUE THREAD

**Issue by ospector** [killbilling/recurly-java-library#73]
for some reason guava is defined as scope=provided.
This leads to issues:
(1) For apps that do not use guava
(2) For apps that use guava version<15 (incompatibility)

Unless such users download the source and run mvn dependency:list, they will not understand the reason as the dependency isn't even listed in their app (as it is "provided").

guava is NOT a library that has a vendor specific provided implementation, neither is it optional.
The scope should be "compile"

**Comment by bhelx** [comment]
This appears to have been resolved with https://github.com/killbilling/recurly-java-library/issues/95

Please re-open if you are still having a problem.

**Comment by pierre** [comment]
@bhelx Actually, Guava is still marked as provided. The original intent was to ease the upgrade from Google collections, but it's probably fine now to mark it as `compile` (we could do the change for the next minor release).

**Comment by hijklmno** [comment]
PR'd #205.

**Comment by aaron-suarez** [comment]
Guava is no longer marked as provided as of https://github.com/killbilling/recurly-java-library/commit/a1beb570763fdb00a2cc3fac76df8047cd9d5e3a

Closing this out. If I misunderstood something, please feel free to reopen
