### ISSUE TITLE
issue: profile integration does not exist.

### ISSUE THREAD

**Issue by jahskee** [killbilling/recurly-java-library#85]
Hi Developers,

I tried running this:

mvn clean test -Pintegration -Dkillbill.payment.recurly.apiKey=xxxxx 
-Dkillbill.payment.recurly.subDomain=mydomain

It returns this error message:
[WARNING] The requested profile "integration" could not be activated because it does not exist.

Anyone have idea?

Thank you,
Jai

**Comment by pierre** [comment]
That's odd. Are you sure you are in the right repo? Have you pulled the latest code?

**Comment by jahskee** [comment]
I am using Eclipse, i added this in my pom.xml, 
http://i.imgur.com/KUcP2RA.png

Following the instruction

Thank you,
Jai

**Comment by pierre** [comment]
The development instructions only apply to working on the library itself, not to a third-party project depending on the jar.

**Comment by jahskee** [comment]
Got this Pierre, sorry i tot that instruction are for 3rd parties. thanks!
