### ISSUE TITLE
com.ning.billing.recurly.model.SubscriptionNotes not found

### ISSUE THREAD

**Issue by jahskee** [killbilling/recurly-java-library#86]
The class 
com.ning.billing.recurly.model.SubscriptionNotes;

is not found in the library i added 0.2.4 i checked the jar its not there.

Can anyone help?

**Comment by pierre** [comment]
You need to use the latest master to access `SubscriptionNotes`, there is no published jar yet with it.

**Comment by jahskee** [comment]
Thanks!
