### ISSUE TITLE
Recurly data models com.ning.billing.recurly.model.* not serializeable

### ISSUE THREAD

**Issue by jahskee** [killbilling/recurly-java-library#88]
Hello i am trying to do recurly api call within Jboss EJB session bean but it returns com.ning.billing.recurly.model.Errors not serializable, Can RecurlyObject.java implement Serializeable class?

Thanks,
Jai

**Comment by pierre** [comment]
Have you tried modifying the library locally? Would it indeed solve your issue(s) (the library hasn't been tested in a JBoss environment)?

If so, feel free to submit a PR.

**Comment by jahskee** [comment]
Yes making com.ning.billing.recurly.model.RecurlyObject implement serializeable fixed the issue.

**Comment by jahskee** [comment]
Thanks for the reply.

**Comment by jahskee** [comment]
Thanks for the reply.

**Comment by bhelx** [comment]
@jahskee @pierre going to go ahead and close this issue. Please re-open if we don't think it's resolved.
