### ISSUE TITLE
missing guava dependency with sbt

### ISSUE THREAD

**Issue by syves** [killbilling/recurly-java-library#95]
When I pull in the library through sbt 
by adding to build.sbt ->
libraryDependencies += "com.ning.billing" % "recurly-java-library" % "0.4.0"

I get this error:

java.lang.NoClassDefFoundError: com/google/common/io/Resources)
java.lang.NoClassDefFoundError: com/google/common/io/Resources
at com.ning.billing.recurly.RecurlyClient.buildUserAgent(RecurlyClient.java:1045)
at com.ning.billing.recurly.RecurlyClient.<init>(RecurlyClient.java:144)

I had to fish around and finally determined I needed ->
libraryDependencies += "com.google.guava" % "guava" % "18.0"

I'm not sure why this isn't included, or pulled in properly. FYI!

**Comment by pierre** [comment]
Duplicate of https://github.com/killbilling/recurly-java-library/issues/73.

**Comment by syves** [comment]
Oh ok!
