### ISSUE TITLE
Coupon Redemptions 

### ISSUE THREAD

**Issue by cbsi-sl** [killbilling/recurly-java-library#97]
Hi, 

Right now the method getCouponRedemptionByAccount() seems to hit this Recurly endpoint:
https://:subdomain.recurly.com/v2/accounts/:account_code/redemption

Recurly seems to also support listing out multiple redemptions, including redemptions that have naturally expired:
https://:subdomain.recurly.com/v2/accounts/:account_code/redemptions

May I ask if the multiple redemptions response will be supported?

thanks.

**Comment by bhelx** [comment]
@cbsi-sl I'll put it on my calendar for next week. I need to investigate the level of effort to required to add it to this library. I think it should be pretty straight forward.

**Comment by cbsi-sl** [comment]
Thanks for helping with this Benjamin!

**Comment by bhelx** [comment]
Closed with https://github.com/killbilling/recurly-java-library/pull/104
