### ISSUE TITLE
Incorrect RootElement for Accounts class

### ISSUE THREAD

**Issue by bhelx** [killbilling/recurly-java-library#98]
This should be `accounts` and not `plans` correct?

https://github.com/killbilling/recurly-java-library/blob/master/src/main/java/com/ning/billing/recurly/model/Accounts.java#L26

```java
@XmlRootElement(name = "plans")
public class Accounts extends RecurlyObjects<Account> {
   //...
}
```

I'm assuming it has not come up because it's only used for serialization and the clients never serialize a list of accounts? I'd be happy to send a fix for this.

\cc @pierre @sbrossie

**Comment by pierre** [comment]
It looks like an [old typo](https://github.com/killbilling/recurly-java-library/commit/49569c71eab6e6306d1ec39828219c8a42db164f) indeed.

Just run the whole test suite with the fix to make sure we didn't miss anything :smile_cat:

**Comment by bhelx** [comment]
Sure thing, already did. Will send a PR on monday morning.

**Comment by bhelx** [comment]
Closed with https://github.com/killbilling/recurly-java-library/pull/99
